import React, { useState, useCallback } from 'react'
import { Layers, Check, Loader2, Zap } from 'lucide-react'

/**
 * AdaptiveCard — Dynamic structured UI generated by the LLM.
 *
 * The model emits `<adaptive-card>{...json...}</adaptive-card>` blocks inside its
 * response. This component renders them as interactive, task-specific cards:
 *   - form:   Input fields, dropdowns, toggles with submit
 *   - data:   Key-value metric grids
 *   - action: Button groups for one-click workflows
 *   - status: Step checklists / progress indicators
 *
 * All elements receive unique IDs and full ARIA labeling. Actions dispatch
 * events to the chat composer (pre-fill prompt on button click).
 */

const CARD_ICONS = {
  form: '📝',
  data: '📊',
  action: '⚡',
  status: '✅',
}

function dispatchPrompt(prompt) {
  window.dispatchEvent(new CustomEvent('yogatik:submit-prompt', { detail: { prompt } }))
}

function FormCard({ body, cardId }) {
  const [values, setValues] = useState({})
  const update = (key, val) => setValues(prev => ({ ...prev, [key]: val }))

  return (
    <div className="ac-form" role="form" aria-label="AI-generated form">
      {body.map((field, i) => {
        const fieldId = `${cardId}-field-${i}`
        return (
          <div key={fieldId} className="ac-form-field">
            <label htmlFor={fieldId}>{field.label || field.name || `Field ${i + 1}`}</label>
            {field.type === 'select' || field.type === 'dropdown' ? (
              <select
                id={fieldId}
                value={values[field.name] || field.default || ''}
                onChange={(e) => update(field.name, e.target.value)}
                aria-label={field.label || field.name}
              >
                {(field.options || []).map((opt, j) => (
                  <option key={j} value={typeof opt === 'string' ? opt : opt.value}>
                    {typeof opt === 'string' ? opt : opt.label}
                  </option>
                ))}
              </select>
            ) : field.type === 'textarea' ? (
              <textarea
                id={fieldId}
                value={values[field.name] || ''}
                onChange={(e) => update(field.name, e.target.value)}
                placeholder={field.placeholder || ''}
                rows={field.rows || 3}
                aria-label={field.label || field.name}
              />
            ) : (
              <input
                id={fieldId}
                type={field.type || 'text'}
                value={values[field.name] || ''}
                onChange={(e) => update(field.name, e.target.value)}
                placeholder={field.placeholder || ''}
                aria-label={field.label || field.name}
              />
            )}
          </div>
        )
      })}
    </div>
  )
}

function DataCard({ body }) {
  return (
    <div className="ac-data-grid" role="group" aria-label="Data metrics">
      {body.map((cell, i) => (
        <div key={i} className="ac-data-cell">
          <span className="ac-cell-label">{cell.label || cell.key}</span>
          <span className="ac-cell-value">{cell.value}</span>
        </div>
      ))}
    </div>
  )
}

function ActionCard({ body }) {
  return (
    <div className="ac-action-bar" role="group" aria-label="Quick actions">
      {body.map((action, i) => (
        <button
          key={i}
          className={`ac-action-btn${action.primary ? ' primary' : ''}`}
          onClick={() => dispatchPrompt(action.prompt || action.label)}
          aria-label={action.label}
        >
          {action.icon && <span>{action.icon}</span>}
          <span>{action.label}</span>
        </button>
      ))}
    </div>
  )
}

function StatusCard({ body }) {
  return (
    <div className="ac-status-track" role="list" aria-label="Progress steps">
      {body.map((step, i) => {
        const state = step.status || step.state || 'pending'
        return (
          <div
            key={i}
            className={`ac-status-step ${state}`}
            role="listitem"
            aria-label={`Step ${i + 1}: ${step.label} — ${state}`}
          >
            <span className="ac-step-indicator" aria-hidden="true">
              {state === 'done' ? <Check size={10} /> : state === 'active' ? <Loader2 size={10} /> : i + 1}
            </span>
            <span>{step.label}</span>
          </div>
        )
      })}
    </div>
  )
}

export function AdaptiveCard({ data, cardIndex = 0 }) {
  if (!data || typeof data !== 'object') return null

  const { type, title, body } = data
  const cardId = `adaptive-card-${cardIndex}`

  if (!Array.isArray(body) || body.length === 0) return null

  return (
    <div className="adaptive-card" id={cardId} role="region" aria-label={title || `Interactive ${type} card`}>
      {title && (
        <div className="ac-title">
          <span className="ac-title-icon" aria-hidden="true">
            {type === 'status' ? <Check size={13} /> : type === 'action' ? <Zap size={13} /> : <Layers size={13} />}
          </span>
          <span>{title}</span>
        </div>
      )}
      {type === 'form' && <FormCard body={body} cardId={cardId} />}
      {type === 'data' && <DataCard body={body} />}
      {type === 'action' && <ActionCard body={body} />}
      {type === 'status' && <StatusCard body={body} />}
      {!['form', 'data', 'action', 'status'].includes(type) && <DataCard body={body} />}
    </div>
  )
}

/**
 * Parse `<adaptive-card>{...json...}</adaptive-card>` blocks from raw text.
 * Returns { parts: [{ type: 'text'|'card', content|data }] }.
 *
 * Graceful: malformed JSON falls back to a code block display.
 */
export function parseAdaptiveCards(text) {
  if (!text || typeof text !== 'string') return { parts: [{ type: 'text', content: text || '' }] }

  const regex = /<adaptive-card>([\s\S]*?)<\/adaptive-card>/gi
  const parts = []
  let lastIndex = 0
  let match

  while ((match = regex.exec(text)) !== null) {
    // Text before the card
    if (match.index > lastIndex) {
      parts.push({ type: 'text', content: text.slice(lastIndex, match.index) })
    }

    // Try to parse the JSON
    const raw = match[1].trim()
    try {
      const data = JSON.parse(raw)
      parts.push({ type: 'card', data })
    } catch {
      // Malformed JSON — render as a code block
      parts.push({ type: 'text', content: `\`\`\`json\n${raw}\n\`\`\`` })
    }

    lastIndex = regex.lastIndex
  }

  // Remaining text after last card
  if (lastIndex < text.length) {
    parts.push({ type: 'text', content: text.slice(lastIndex) })
  }

  // No cards found at all
  if (parts.length === 0) {
    parts.push({ type: 'text', content: text })
  }

  return { parts }
}
