import React, { useState, useCallback, useMemo, useEffect, useRef } from 'react'
import { splitReasoning } from '../reasoning'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import {
  Volume2, Wrench, Copy, Check, RefreshCw, Pencil, AlertTriangle,
  FileDown, FileText, Download, Zap, Key, Settings, HelpCircle,
  ChevronDown, ChevronUp, ShieldAlert, Cpu
} from 'lucide-react'
import { CodeBlock } from './CodeBlock'
import { exportPptx } from '../tools/independentTools'
import { mdToHtml } from '../tools/mdToPdf'
import { ToolResultCard, TOOL_ICONS } from './ToolResultCard'
import { diagnoseError } from '../errorLog'

/**
 * "Why did I say this" — a plain-language summary of what shaped the reply
 * (tools run, sources consulted, model). Transparency deliverable from the audit;
 * complements the step list below with a one-liner a non-technical user reads.
 */
function explainReply(msg, modelName) {
  const bits = []
  const tools = msg.toolsUsed || []
  if (tools.length) bits.push(`used ${tools.length === 1 ? 'the tool' : 'tools'} ${tools.join(', ')}`)
  const nSources = msg.sources?.length || 0
  if (nSources) bits.push(`consulted ${nSources} source${nSources === 1 ? '' : 's'}`)
  if (!bits.length) return `Answered directly from the model${modelName ? ` (${modelName})` : ''}, with no tools or web sources.`
  return `This reply ${bits.join(' and ')}${modelName ? `, generated by ${modelName}` : ''}.`
}

/** "just now", "4m", "2h", then a date. */
function relativeTime(ts) {
  if (!ts) return ''
  const s = Math.floor((Date.now() - ts) / 1000)
  if (s < 60) return 'just now'
  if (s < 3600) return `${Math.floor(s / 60)}m ago`
  if (s < 86400) return `${Math.floor(s / 3600)}h ago`
  return new Date(ts).toLocaleDateString()
}

async function triggerDownload(text, format = 'doc', defaultTitle = 'Document') {
  let content = text
  let mimeType = 'text/plain'
  let ext = format

  if (format === 'ppt' || format === 'pptx' || format === 'presentation') {
    exportPptx(text, defaultTitle, true)
    return
  } else if (format === 'csv') {
    ext = 'csv'
    mimeType = 'text/csv;charset=utf-8;'
    if (text.includes('|')) {
      const lines = text.split('\n').filter(l => l.trim().startsWith('|') && !l.includes('---'))
      content = '\uFEFF' + lines.map(l => l.split('|').slice(1, -1).map(c => `"${c.trim().replace(/"/g, '""')}"`).join(',')).join('\n')
    } else {
      content = '\uFEFF' + text
    }
  } else if (format === 'doc' || format === 'docx' || format === 'word' || format === 'rtf') {
    ext = 'doc'
    mimeType = 'application/msword'
    const cleanTitle = defaultTitle.replace(/\.(rtf|doc|docx|txt)$/i, '')
    const htmlBody = mdToHtml(text)
    content = `<!DOCTYPE html><html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'><head><meta charset='utf-8'><title>${cleanTitle}</title><style>body{font-family:'Calibri','Segoe UI',sans-serif;font-size:11pt;line-height:1.6;color:#1e293b;margin:1in;}h1{font-size:22pt;color:#0f172a;border-bottom:2px solid #38bdf8;padding-bottom:6pt;margin-top:14pt;margin-bottom:12pt;}h2{font-size:16pt;color:#1e3a8a;margin-top:14pt;border-bottom:1px solid #cbd5e1;padding-bottom:4pt;margin-bottom:8pt;}h3{font-size:13pt;color:#0284c7;margin-top:10pt;}p{margin-bottom:8pt;}ul,ol{margin:6pt 0 8pt 20pt;}li{margin-bottom:3pt;}code{font-family:Consolas,monospace;background:#f1f5f9;padding:2px 5px;border-radius:3px;color:#0f172a;}pre{background:#0f172a;color:#f8fafc;padding:12px;border-radius:6px;}table{border-collapse:collapse;width:100%;margin:12pt 0;}th,td{border:1px solid #cbd5e1;padding:8px 10px;text-align:left;}th{background:#1e293b;color:#ffffff;font-weight:bold;}tr:nth-child(even){background:#f8fafc;}blockquote{border-left:4px solid #38bdf8;background:#f0f9ff;margin:10pt 0;padding:8pt 12pt;color:#0369a1;font-style:italic;}</style></head><body><h1>${cleanTitle}</h1><p style='color:#64748b;font-size:9.5pt;margin-bottom:18pt;'>Generated by Yogatik Intelligence Engine • ${new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}</p><hr style='border:none;border-top:1px solid #e2e8f0;margin-bottom:18pt;'/>${htmlBody}</body></html>`
  } else if (format === 'html') {
    ext = 'html'
    mimeType = 'text/html'
    const cleanTitle = defaultTitle.replace(/\.html$/i, '')
    const htmlBody = mdToHtml(text)
    content = `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${cleanTitle}</title><style>body{font-family:Inter,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;line-height:1.6;padding:2.5rem 1.5rem;max-width:880px;margin:0 auto;color:#1e293b;background:#f8fafc;}h1{color:#0f172a;border-bottom:2px solid #38bdf8;padding-bottom:8px;}h2{color:#1e3a8a;margin-top:24px;border-bottom:1px solid #e2e8f0;padding-bottom:6px;}h3{color:#0284c7;}table{border-collapse:collapse;width:100%;margin:1.5rem 0;}th,td{border:1px solid #e2e8f0;padding:8px 12px;text-align:left;}th{background:#1e293b;color:#fff;}tr:nth-child(even){background:#f1f5f9;}blockquote{border-left:4px solid #38bdf8;background:#f0f9ff;padding:0.75rem 1.25rem;color:#0369a1;border-radius:0 6px 6px 0;margin:1.25rem 0;}code{background:#e2e8f0;padding:2px 6px;border-radius:4px;font-family:Consolas,monospace;}pre{background:#0f172a;color:#f8fafc;padding:1rem;border-radius:8px;overflow-x:auto;}</style></head><body><h1>${cleanTitle}</h1>${htmlBody}</body></html>`
  } else if (format === 'md') {
    ext = 'md'
    mimeType = 'text/markdown'
  } else if (format === 'pdf') {
    const cleanTitle = defaultTitle.replace(/\.pdf$/i, '')
    const htmlBody = mdToHtml(text)
    const container = document.createElement('div')
    container.innerHTML = `<style>body{font-family:Inter,-apple-system,Segoe UI,Roboto,sans-serif;color:#1e293b;font-size:11pt;line-height:1.6;}h1{font-size:22pt;color:#0f172a;border-bottom:2px solid #38bdf8;padding-bottom:6px;margin:0 0 12px 0;}h2{font-size:15pt;color:#1e3a8a;margin:20px 0 8px 0;border-bottom:1px solid #e2e8f0;padding-bottom:4px;page-break-after:avoid;}h3{font-size:13pt;color:#0284c7;margin:14px 0 6px 0;page-break-after:avoid;}table{border-collapse:collapse;width:100%;margin:14px 0;page-break-inside:avoid;}th,td{border:1px solid #cbd5e1;padding:7px 10px;text-align:left;}th{background:#1e293b;color:#ffffff;font-weight:bold;}tr:nth-child(even){background:#f8fafc;}blockquote{border-left:4px solid #38bdf8;margin:12px 0;padding:8px 14px;background:#f0f9ff;color:#0369a1;page-break-inside:avoid;}pre{background:#0f172a;color:#f8fafc;padding:12px;border-radius:6px;font-size:9.5pt;page-break-inside:avoid;}</style><h1>${cleanTitle}</h1><p style='color:#64748b;font-size:9pt;margin-bottom:16px;'>Generated by Yogatik Intelligence Engine • ${new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}</p><hr style='border:none;border-top:1px solid #e2e8f0;margin-bottom:16px;'/>${htmlBody}`
    container.style.cssText = 'padding:14mm 12mm;background:#fff;'

    if (!window.html2pdf) {
      const s = document.createElement('script')
      s.src = 'https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.2/html2pdf.bundle.min.js'
      document.head.appendChild(s)
      await new Promise((res) => { s.onload = res; s.onerror = res })
    }

    if (window.html2pdf) {
      window.html2pdf().from(container).set({
        margin: 0,
        filename: `${cleanTitle}.pdf`,
        html2canvas: { scale: 2, useCORS: true, backgroundColor: '#ffffff' },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['css', 'legacy'] },
      }).save()
      return
    }

    const printWin = window.open('', '_blank')
    if (printWin) {
      printWin.document.write(`<!DOCTYPE html><html><head><title>${cleanTitle}</title><style>body{font-family:sans-serif;padding:30px;line-height:1.6;color:#222;}</style></head><body>${container.innerHTML}<script>window.print();<\/script></body></html>`)
      printWin.document.close()
    }
    return
  }

  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${defaultTitle.replace(/[^a-z0-9_-]/gi, '_')}.${ext}`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

/**
 * Build a stable ReactMarkdown `components` map. Defined once per MessageBubble
 * instance (not inline per render), so React.memo can actually skip re-renders.
 */
function useMarkdownComponents(msgContent, onOpenArtifact) {
  return useMemo(() => ({
    a({ node, href, children, ...props }) {
      const rawLabel = typeof children === 'string'
        ? children.trim()
        : Array.isArray(children)
          ? children.map(c => typeof c === 'string' ? c : '').join('').trim()
          : String(children || '').trim()
      const cleanLabel = rawLabel.replace(/^download\s+/i, '').trim()
      const hrefStr = typeof href === 'string' ? href : ''
      const isDocLink = (hrefStr && hrefStr.match(/\.(rtf|doc|docx|ppt|pptx|pdf|csv|html|txt)($|\?)/i)) ||
                        (rawLabel && rawLabel.match(/\.(rtf|doc|docx|ppt|pptx|pdf|csv|html|txt)\b/i))
      if (isDocLink || hrefStr.startsWith('data:') || hrefStr.startsWith('blob:')) {
        const format = rawLabel.match(/\.(ppt|pptx)/i) || hrefStr.match(/\.(ppt|pptx)/i)
          ? 'ppt'
          : rawLabel.match(/\.(rtf|doc|docx)/i) || hrefStr.match(/\.(rtf|doc|docx)/i)
            ? 'doc'
            : rawLabel.match(/\.pdf/i) || hrefStr.match(/\.pdf/i)
              ? 'pdf'
              : rawLabel.match(/\.csv/i) || hrefStr.match(/\.csv/i)
                ? 'csv'
                : 'doc'
        return (
          <button
            className="inline-download-btn"
            onClick={(e) => {
              e.preventDefault()
              triggerDownload(msgContent, format, cleanLabel.replace(/\.(rtf|doc|docx|ppt|pptx|pdf|csv)$/i, '') || 'document')
            }}
            style={{
              display: 'inline-flex', alignItems: 'center', gap: 6,
              background: 'linear-gradient(135deg, #ff6b35, #ff8c42)', color: '#fff',
              border: 'none', padding: '6px 14px', borderRadius: 8,
              fontWeight: 600, fontSize: 13, cursor: 'pointer', margin: '8px 0',
              boxShadow: '0 2px 8px rgba(255,107,53,0.3)',
            }}
          >
            <FileDown size={14} /> Download {cleanLabel || 'Presentation'}
          </button>
        )
      }
      return <a href={href} target="_blank" rel="noopener noreferrer" className="chat-link" {...props}>{children}</a>
    },
    code({ node, inline, className, children, ...props }) {
      return !inline ? (
        <CodeBlock className={className} onOpenArtifact={onOpenArtifact}>{children}</CodeBlock>
      ) : (
        <code className={className} {...props}>{children}</code>
      )
    }
  // msgContent changes when the message changes, onOpenArtifact is stable
  }), [msgContent, onOpenArtifact])
}

const MessageBubble = React.memo(function MessageBubble({
   msg, onTTS, onOpenArtifact, onRegenerate, onEdit, onRetry, onOpenSettings, onAutoPick, showToolCards = true,
}) {
   const [copied, setCopied] = useState(false)
   const [showExportMenu, setShowExportMenu] = useState(false)
   // Default EXPANDED: collapsing by default hid whole answers behind "Show more".
   const [isExpanded, setIsExpanded] = useState(true)
   const exportMenuRef = useRef(null)

  // Close export dropdown when clicking outside it
  useEffect(() => {
    if (!showExportMenu) return
    const handler = (e) => {
      if (exportMenuRef.current && !exportMenuRef.current.contains(e.target)) {
        setShowExportMenu(false)
      }
    }
    document.addEventListener('mousedown', handler)
    return () => document.removeEventListener('mousedown', handler)
  }, [showExportMenu])

  const copy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(msg.content)
      setCopied(true)
      setTimeout(() => setCopied(false), 1500)
    } catch { /* clipboard blocked — nothing useful to say */ }
  }, [msg.content])

  // Build stable markdown components config — avoids new object on every render
  const markdownComponents = useMarkdownComponents(msg.content, onOpenArtifact)

  const formattedModelName = useMemo(() => {
    const rawModel = msg.model || ''
    const rawProv = msg.provider || ''
    const mName = rawModel ? rawModel.split('/').pop() : ''
    const pName = rawProv === 'nvidia' ? 'NVIDIA (Free)'
      : rawProv === 'ollama' ? 'Ollama (local)'
      : rawProv === 'openrouter' ? 'OpenRouter'
      : rawProv === 'groq' ? 'Groq'
      : rawProv === 'openai' ? 'OpenAI'
      : rawProv === 'gemini' ? 'Gemini'
      : rawProv === 'anthropic' ? 'Anthropic Claude'
      : rawProv === 'deepseek' ? 'DeepSeek'
      : rawProv === 'xai' ? 'xAI Grok'
      : rawProv === 'mistral' ? 'Mistral AI'
      : rawProv === 'perplexity' ? 'Perplexity'
      : rawProv === 'local' ? 'On-device Model'
      : rawProv
    if (pName && mName) return `${pName} · ${mName}`
    if (mName) return mName
    if (pName) return pName
    return 'AI Model'
  }, [msg.model, msg.provider])

  let reasoning = '', answer = typeof msg.content === 'string' ? msg.content : String(msg.content ?? '')

  // Failed turns are rendered with actionable diagnosis, resolution recommendations, and copy tools
  if (msg.error) {
    const diagnosis = diagnoseError(msg.error)
    return (
      <div className="message assistant message-failed" role="alert">
        <div className="message-error-card">
          <div className="message-error-header">
            <div className="message-error-title-wrap">
              <span className={`error-category-badge badge-${diagnosis.type}`}>
                {diagnosis.category}
              </span>
              <h4 className="message-error-title">{diagnosis.title}</h4>
            </div>
            <div className="message-error-actions">
              <button
                type="button"
                className="error-action-btn error-copy-btn"
                onClick={async () => {
                  try {
                    const dump = `Error: ${diagnosis.title}\nCategory: ${diagnosis.category}\nModel: ${msg.model || 'Unknown'}\nProvider: ${msg.provider || 'Unknown'}\nDetails: ${msg.error}`
                    await navigator.clipboard.writeText(dump)
                    setCopied(true)
                    setTimeout(() => setCopied(false), 2000)
                  } catch {}
                }}
                title="Copy error details"
              >
                {copied ? <Check size={12} /> : <Copy size={12} />}
                <span>{copied ? 'Copied' : 'Copy'}</span>
              </button>
            </div>
          </div>

          <div className="message-error-suggestion">
            {diagnosis.suggestion}
          </div>

          <div className="message-error-buttons">
            {onRetry && (
              <button type="button" className="error-btn-primary" onClick={onRetry}>
                <RefreshCw size={13} /> Retry Turn
              </button>
            )}

            {(diagnosis.actionType === 'settings' || diagnosis.type === 'auth') && onOpenSettings && (
              <button type="button" className="error-btn-secondary" onClick={onOpenSettings}>
                <Key size={13} /> {diagnosis.actionLabel || 'Configure Keys'}
              </button>
            )}

            {(diagnosis.actionType === 'autopick' || diagnosis.type === 'quota' || diagnosis.type === 'model_not_found') && onAutoPick && (
              <button type="button" className="error-btn-secondary" onClick={onAutoPick}>
                <Zap size={13} /> {diagnosis.actionLabel || 'Auto-Pick Model'}
              </button>
            )}
          </div>

          <details className="message-error-trace">
            <summary>
              <span>Technical Diagnostics</span>
            </summary>
            <pre className="message-error-raw">{msg.error}</pre>
          </details>
        </div>
      </div>
    )
  }

  return (
    <div className={`message ${msg.role}`}>
      <div className="message-role">
        <span className="message-who">{msg.role === 'user' ? 'You' : 'Yogatik'}</span>
        {msg.role === 'assistant' && (
          <span className="msg-model-badge" title={`Generated by ${formattedModelName}`}>
            {formattedModelName}
          </span>
        )}
        {msg.createdAt && <time className="message-time" dateTime={new Date(msg.createdAt).toISOString()}>{relativeTime(msg.createdAt)}</time>}

        <span className="message-actions" style={{ position: 'relative' }}>
          <button className="icon-btn" onClick={copy} title="Copy" aria-label="Copy message">
            {copied ? <Check size={12} /> : <Copy size={12} />}
          </button>
          {msg.role === 'assistant' && (
            <>
              <button className="icon-btn" onClick={() => onTTS(msg.content)} title="Read aloud" aria-label="Read aloud">
                <Volume2 size={12} />
              </button>
              <span ref={exportMenuRef} style={{ position: 'relative' }}>
                <button
                  className="icon-btn"
                  onClick={() => setShowExportMenu(v => !v)}
                  title="Download as Word / PDF / MD"
                  aria-label="Download message"
                  aria-haspopup="true"
                  aria-expanded={showExportMenu}
                >
                  <Download size={12} />
                </button>
                {showExportMenu && (
                  <div
                    className="export-dropdown"
                    role="menu"
                    style={{
                      position: 'absolute', top: '100%', right: 0, zIndex: 100,
                      background: 'var(--bg-secondary, #1e1e2e)', border: '1px solid var(--border-color, rgba(255,255,255,0.1))',
                      borderRadius: 6, boxShadow: '0 4px 12px rgba(0,0,0,0.3)', padding: 4, display: 'flex', flexDirection: 'column', gap: 2, minWidth: 140,
                    }}
                  >
                    {[
                      { fmt: 'doc',          label: 'Word Document (.doc)',    icon: <FileText size={12} />,  title: 'document' },
                      { fmt: 'ppt',          label: 'PowerPoint (.ppt)',       icon: <FileText size={12} />,  title: 'presentation' },
                      { fmt: 'csv',          label: 'CSV Spreadsheet (.csv)',  icon: <FileText size={12} />,  title: 'data' },
                      { fmt: 'pdf',          label: 'PDF (.pdf)',              icon: <FileDown size={12} />,  title: 'document' },
                      { fmt: 'md',           label: 'Markdown (.md)',          icon: <Download size={12} />,  title: 'document' },
                    ].map(({ fmt, label, icon, title }) => (
                      <button
                        key={fmt}
                        role="menuitem"
                        className="dropdown-item"
                        onClick={() => { triggerDownload(msg.content, fmt, title); setShowExportMenu(false) }}
                        style={{ background: 'none', border: 'none', color: 'var(--text-primary)', padding: '6px 10px', fontSize: 12, textAlign: 'left', cursor: 'pointer', borderRadius: 4, display: 'flex', alignItems: 'center', gap: 6 }}
                      >
                        {icon} {label}
                      </button>
                    ))}
                  </div>
                )}
              </span>
            </>
          )}
          {msg.role === 'assistant' && onRegenerate && (
            <button className="icon-btn" onClick={onRegenerate} title="Regenerate" aria-label="Regenerate this reply">
              <RefreshCw size={12} />
            </button>
          )}
          {msg.role === 'user' && onEdit && (
            <button className="icon-btn" onClick={() => onEdit(typeof msg.content === 'string' ? msg.content : '')}
              title="Edit this message — earlier turns branch into a new chat, the original is kept"
              aria-label="Edit this message">
              <Pencil size={12} />
            </button>
          )}
        </span>
      </div>

      {showToolCards && msg.toolResults && Object.keys(msg.toolResults).length > 0 && (
        <div className="tool-results">
          {Object.entries(msg.toolResults).map(([tool, result]) => (
            <ToolResultCard key={tool} tool={tool} result={result} />
          ))}
        </div>
      )}
      {msg.toolsUsed?.length > 0 && (
        <div className="tools-used">
          {msg.toolsUsed.map(t => {
            const Icon = TOOL_ICONS[t] || Wrench
            return <span key={t} className="tool-chip"><Icon size={10} /> {t}</span>
          })}
        </div>
      )}
      {msg.role === 'assistant' && (
        <details className="activity-trace">
          <summary>Steps, thoughts & actions taken ({msg.trace?.length || 1} step{(msg.trace?.length || 1) === 1 ? '' : 's'})</summary>
          <p className="why-explain">{explainReply(msg, formattedModelName)}</p>
          <ol>
            {msg.trace?.length > 0 ? (
              msg.trace.map((s, i) => {
                const Icon = TOOL_ICONS[s.tool] || Wrench
                const arg = s.args && Object.keys(s.args).length
                  ? JSON.stringify(s.args).replace(/^{|}$/g, '').slice(0, 180)
                  : ''
                const mark = s.status === 'error' ? '✕ Failed' : s.status === 'done' ? '✓ Completed' : '… In progress'
                return (
                  <li key={i} className={`trace-step trace-${s.status}`}>
                    <Icon size={11} /> <span className="trace-tool">Step {i + 1}: Executed {s.tool}</span>
                    {arg && <div className="trace-args" style={{ fontSize: '10.5px', opacity: 0.85, marginTop: '2px' }}>Input: {arg}</div>}
                    <span className="trace-mark" style={{ fontSize: '10px', marginLeft: 'auto', fontWeight: 600 }}>{mark}</span>
                  </li>
                )
              })
            ) : (
              <li className="trace-step trace-done">
                <Wrench size={11} /> <span className="trace-tool">Step 1: Direct response generation ({formattedModelName})</span>
                <span className="trace-mark" style={{ fontSize: '10px', marginLeft: 'auto', fontWeight: 600 }}>✓ Completed</span>
              </li>
            )}
          </ol>
        </details>
      )}
      {msg.image && (
        <img src={msg.image} alt="Attached image" className="msg-image"
          onClick={() => window.open(msg.image, '_blank', 'noopener')} />
      )}
      {(() => { const s = splitReasoning(typeof msg.content === 'string' ? msg.content : String(msg.content ?? '')); reasoning = s.reasoning; answer = s.answer; return null })()}
      {reasoning && (
        <details className="reasoning-panel">
          <summary>Thinking</summary>
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{reasoning}</ReactMarkdown>
        </details>
      )}
      {/* A successful turn with no visible answer (e.g. reasoning-only) must not
          render blank — say so instead of looking broken. */}
      {msg.role === 'assistant' && typeof answer === 'string' && !answer && (
        <div className="message-content message-empty">
          {reasoning ? '(The model returned only reasoning — no final answer.)'
                     : '(The model returned an empty response. Try Regenerate or a stronger model.)'}
        </div>
      )}
       {/* Check if message content is long enough to warrant collapsing */}
       {typeof answer === 'string' && answer.length > 500 && msg.role === 'assistant' ? (
         <div className="message-content">
           {!isExpanded && (
             <>
               <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
                 {answer.substring(0, 500)}...
               </ReactMarkdown>
               <button
                 className="message-toggle-btn"
                 onClick={() => setIsExpanded(true)}
               >
                 Show more
               </button>
             </>
           )}
           {isExpanded && (
             <>
               <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
                 {answer}
               </ReactMarkdown>
               <button
                 className="message-toggle-btn"
                 onClick={() => setIsExpanded(false)}
               >
                 Show less
               </button>
             </>
           )}
         </div>
        ) : (
         <div className="message-content">
            <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>{answer}</ReactMarkdown>
          </div>
        )}
      {msg.sources?.length > 0 && (
        <div className="sources">
          <div className="sources-title">Sources</div>
          {msg.sources.filter(s => s.url).map((s, i) => (
            <div key={i} className="source-item">
              <a href={s.url} target="_blank" rel="noopener">{s.title || s.url}</a>
            </div>
          ))}
        </div>
      )}
    </div>
  )
})

export { MessageBubble }
