import React, { useState, useCallback, useMemo, useEffect, useRef } from 'react'
import { splitReasoning } from '../reasoning'
import { stripToolCallSyntax } from '../promptedTools'
import { extractActionChips } from '../actionChips'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import {
  Volume2, Wrench, Copy, Check, RefreshCw, Pencil, AlertTriangle,
  FileDown, FileText, Download, Zap, Key, Settings, HelpCircle,
  ChevronDown, ChevronUp, ShieldAlert, Cpu, Play, Info
} from 'lucide-react'
import { CodeBlock } from './CodeBlock'
import { exportPptx } from '../tools/independentTools'
import { mdToHtml } from '../tools/mdToPdf'
import { ToolResultCard, TOOL_ICONS } from './ToolResultCard'
import { diagnoseError } from '../errorLog'
import { AdaptiveCard, parseAdaptiveCards } from './AdaptiveCard'
import { ReasoningAccordion } from './ReasoningAccordion'
import { AgentWorkflowStepper } from './AgentWorkflowStepper'
import { FollowUpSuggestions } from './FollowUpSuggestions'
import { CitationHoverCard } from './CitationHoverCard'

/**
 * "Why did I say this" — a plain-language summary of what shaped the reply
 * (tools run, sources consulted, model). Transparency deliverable from the audit;
 * complements the step list below with a one-liner a non-technical user reads.
 */
function explainReply(msg, modelName) {
  const bits = []
  const tools = msg.toolsUsed || []
  if (tools.length) bits.push(`used ${tools.length === 1 ? 'the tool' : 'tools'} ${tools.join(', ')}`)
  const nSources = msg.sources?.length || 0
  if (nSources) bits.push(`consulted ${nSources} source${nSources === 1 ? '' : 's'}`)
  if (!bits.length) return `Answered directly from the model${modelName ? ` (${modelName})` : ''}, with no tools or web sources.`
  return `This reply ${bits.join(' and ')}${modelName ? `, generated by ${modelName}` : ''}.`
}

/** "just now", "4m", "2h", then a date. */
function relativeTime(ts) {
  if (!ts) return ''
  const s = Math.floor((Date.now() - ts) / 1000)
  if (s < 60) return 'just now'
  if (s < 3600) return `${Math.floor(s / 60)}m ago`
  if (s < 86400) return `${Math.floor(s / 3600)}h ago`
  return new Date(ts).toLocaleDateString()
}

async function triggerDownload(text, format = 'docx', defaultTitle = 'Document') {
  let content = text
  let mimeType = 'text/plain'
  let ext = format

  if (format === 'ppt' || format === 'pptx' || format === 'presentation') {
    exportPptx(text, defaultTitle, true)
    return
  } else if (format === 'xlsx' || format === 'xls' || format === 'excel') {
    const { generateExcelWorkbook } = await import('../tools/docGenerator')
    const res = generateExcelWorkbook({ title: defaultTitle, content: text })
    const a = document.createElement('a')
    a.href = res.data_url
    a.download = res.filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    return
  } else if (format === 'csv') {
    ext = 'csv'
    mimeType = 'text/csv;charset=utf-8;'
    if (text.includes('|')) {
      const lines = text.split('\n').filter(l => l.trim().startsWith('|') && !l.includes('---'))
      content = '\uFEFF' + lines.map(l => l.split('|').slice(1, -1).map(c => `"${c.trim().replace(/"/g, '""')}"`).join(',')).join('\n')
    } else {
      content = '\uFEFF' + text
    }
  } else if (format === 'doc' || format === 'docx' || format === 'word' || format === 'rtf') {
    const { generateWordDoc } = await import('../tools/docGenerator')
    const res = generateWordDoc({ title: defaultTitle, content: text, format: format === 'doc' ? 'doc' : 'docx' })
    const a = document.createElement('a')
    a.href = res.data_url
    a.download = res.filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    return
  } else if (format === 'md' || format === 'markdown') {
    ext = 'md'
    mimeType = 'text/markdown;charset=utf-8;'
    const cleanTitle = defaultTitle.replace(/\.md$/i, '')
    const dateStr = new Date().toISOString().split('T')[0]
    if (!text.trim().startsWith('---')) {
      content = `---\ntitle: "${cleanTitle}"\nauthor: "Yogatik AI"\ndate: "${dateStr}"\nversion: "1.0.0"\n---\n\n${text}`
    } else {
      content = text
    }
  } else if (format === 'html') {
    ext = 'html'
    mimeType = 'text/html'
    const cleanTitle = defaultTitle.replace(/\.html$/i, '')
    const htmlBody = mdToHtml(text)
    content = `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${cleanTitle}</title><style>body{font-family:Inter,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;line-height:1.6;padding:2.5rem 1.5rem;max-width:880px;margin:0 auto;color:#1e293b;background:#f8fafc;}h1{color:#0f172a;border-bottom:2px solid #38bdf8;padding-bottom:8px;}h2{color:#1e3a8a;margin-top:24px;border-bottom:1px solid #e2e8f0;padding-bottom:6px;}h3{color:#0284c7;}table{border-collapse:collapse;width:100%;margin:1.5rem 0;}th,td{border:1px solid #e2e8f0;padding:8px 12px;text-align:left;}th{background:#1e293b;color:#fff;}tr:nth-child(even){background:#f1f5f9;}blockquote{border-left:4px solid #38bdf8;background:#f0f9ff;padding:0.75rem 1.25rem;color:#0369a1;border-radius:0 6px 6px 0;margin:1.25rem 0;}code{background:#e2e8f0;padding:2px 6px;border-radius:4px;font-family:Consolas,monospace;}pre{background:#0f172a;color:#f8fafc;padding:1rem;border-radius:8px;overflow-x:auto;}</style></head><body><h1>${cleanTitle}</h1>${htmlBody}</body></html>`
  } else if (format === 'pdf') {
    const cleanTitle = defaultTitle.replace(/\.pdf$/i, '')
    const { generatePdfDoc } = await import('../tools/docGenerator')
    const res = await generatePdfDoc({ title: cleanTitle, content: text, author: 'Yogatik AI' })
    const a = document.createElement('a')
    a.href = res.data_url
    a.download = res.filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    return
  }

  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${defaultTitle.replace(/[^a-z0-9_-]/gi, '_')}.${ext}`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

/**
 * Build a stable ReactMarkdown `components` map. Defined once per MessageBubble
 * instance (not inline per render), so React.memo can actually skip re-renders.
 */
function useMarkdownComponents(msgContent, onOpenArtifact) {
  return useMemo(() => ({
    a({ node, href, children, ...props }) {
      const rawLabel = typeof children === 'string'
        ? children.trim()
        : Array.isArray(children)
          ? children.map(c => typeof c === 'string' ? c : '').join('').trim()
          : String(children || '').trim()
      const cleanLabel = rawLabel.replace(/^download\s+/i, '').trim()
      const hrefStr = typeof href === 'string' ? href : ''

      // 1. YouTube Video Embeds
      const cleanHref = hrefStr.replace(/[.,;:!?)\]]+$/, '')
      const ytMatch = cleanHref.match(/(?:youtube\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=|shorts\/)|youtu\.be\/)([a-zA-Z0-9_-]{11})(?:[?&/#]|$)/i)
      if (ytMatch && ytMatch[1]) {
        const vidId = ytMatch[1]
        return (
          <div className="chat-inline-video-wrap" style={{ margin: '12px 0', maxWidth: '560px', width: '100%' }}>
            <div style={{ position: 'relative', paddingBottom: '56.25%', height: 0, overflow: 'hidden', borderRadius: '10px', boxShadow: '0 4px 14px rgba(0,0,0,0.3)', background: '#111' }}>
              <iframe
                src={`https://www.youtube-nocookie.com/embed/${vidId}?rel=0`}
                title="YouTube video player"
                frameBorder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                referrerPolicy="strict-origin-when-cross-origin"
                allowFullScreen
                style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', border: 0 }}
              />
            </div>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: '6px', fontSize: '11.5px' }}>
              <a
                href={`https://www.youtube.com/watch?v=${vidId}`}
                target="_blank"
                rel="noopener noreferrer"
                className="chat-link"
                style={{ opacity: 0.85, fontWeight: 500 }}
              >
                ▶ Watch "{children || 'Video'}" on YouTube
              </a>
              <span style={{ fontSize: '10px', opacity: 0.5 }}>(If video is restricted by creator, click link to open)</span>
            </div>
          </div>
        )
      }

      // 2. Direct Video Files (.mp4, .webm, .ogg, .mov)
      if (hrefStr.match(/\.(mp4|webm|ogg|mov)($|\?)/i)) {
        return (
          <div className="chat-inline-video-wrap" style={{ margin: '12px 0', maxWidth: '560px', width: '100%' }}>
            <video
              src={hrefStr}
              controls
              playsInline
              preload="metadata"
              style={{ width: '100%', maxHeight: '400px', borderRadius: '10px', background: '#000', boxShadow: '0 4px 14px rgba(0,0,0,0.3)' }}
            />
            <div style={{ marginTop: '4px' }}>
              <a href={href} target="_blank" rel="noopener noreferrer" className="chat-link" style={{ fontSize: '11px', opacity: 0.8 }}>
                ▶ Open video source
              </a>
            </div>
          </div>
        )
      }

      // 3. Document Download Links (.docx, .doc, .xlsx, .xls, .pptx, .ppt, .pdf, .md, .csv)
      const isDocLink = (hrefStr && hrefStr.match(/\.(rtf|doc|docx|ppt|pptx|xlsx|xls|excel|pdf|csv|md|html|txt)($|\?)/i)) ||
                        (rawLabel && rawLabel.match(/\.(rtf|doc|docx|ppt|pptx|xlsx|xls|excel|pdf|csv|md|html|txt)\b/i))
      if (isDocLink || hrefStr.startsWith('data:') || hrefStr.startsWith('blob:')) {
        const format = rawLabel.match(/\.(ppt|pptx)/i) || hrefStr.match(/\.(ppt|pptx)/i)
          ? 'pptx'
          : rawLabel.match(/\.(xlsx|xls|excel)/i) || hrefStr.match(/\.(xlsx|xls|excel)/i)
            ? 'xlsx'
            : rawLabel.match(/\.(rtf|doc|docx)/i) || hrefStr.match(/\.(rtf|doc|docx)/i)
              ? 'docx'
              : rawLabel.match(/\.pdf/i) || hrefStr.match(/\.pdf/i)
                ? 'pdf'
                : rawLabel.match(/\.md/i) || hrefStr.match(/\.md/i)
                  ? 'md'
                  : rawLabel.match(/\.csv/i) || hrefStr.match(/\.csv/i)
                    ? 'csv'
                    : 'docx'
        return (
          <button
            className="inline-download-btn"
            onClick={(e) => {
              e.preventDefault()
              triggerDownload(msgContent, format, cleanLabel.replace(/\.(rtf|doc|docx|ppt|pptx|xlsx|xls|excel|pdf|csv|md)$/i, '') || 'document')
            }}
            style={{
              display: 'inline-flex', alignItems: 'center', gap: 6,
              background: 'linear-gradient(135deg, #ff6b35, #ff8c42)', color: '#fff',
              border: 'none', padding: '6px 14px', borderRadius: 8,
              fontWeight: 600, fontSize: 13, cursor: 'pointer', margin: '8px 0',
              boxShadow: '0 2px 8px rgba(255,107,53,0.3)',
            }}
          >
            <FileDown size={14} /> Download {cleanLabel || 'Document'}
          </button>
        )
      }
      return <a href={href} target="_blank" rel="noopener noreferrer" className="chat-link" {...props}>{children}</a>
    },
    img({ src, alt, ...props }) {
      const srcStr = typeof src === 'string' ? src : ''
      if (srcStr.match(/\.(mp4|webm|ogg|mov)($|\?)/i)) {
        return (
          <video
            src={srcStr}
            controls
            playsInline
            preload="metadata"
            style={{ width: '100%', maxWidth: '560px', maxHeight: '420px', borderRadius: '10px', background: '#000', margin: '8px 0' }}
          />
        )
      }
      return <img src={src} alt={alt || ''} className="chat-inline-img" style={{ maxWidth: '100%', maxHeight: '400px', borderRadius: '8px', margin: '8px 0' }} {...props} />
    },
    p({ node, children, ...props }) {
      return <div className="md-p" {...props}>{children}</div>
    },
    pre({ children }) {
      return <>{children}</>
    },
    code({ node, inline, className, children, ...props }) {
      const match = /language-(\w+)/.exec(className || '')
      const isMultiLine = String(children || '').includes('\n')
      const isBlock = !inline && (Boolean(match) || isMultiLine)
      return isBlock ? (
        <CodeBlock className={className} onOpenArtifact={onOpenArtifact}>{children}</CodeBlock>
      ) : (
        <code className={className} {...props}>{children}</code>
      )
    }
  // msgContent changes when the message changes, onOpenArtifact is stable
  }), [msgContent, onOpenArtifact])
}

const MessageBubble = React.memo(function MessageBubble({
   msg, onTTS, onOpenArtifact, onRegenerate, onContinue, onEdit, onRetry, onOpenSettings, onAutoPick, showToolCards = true,
}) {
   const [copied, setCopied] = useState(false)
   const [showExportMenu, setShowExportMenu] = useState(false)
   const [showExportMenuBottom, setShowExportMenuBottom] = useState(false)
   // Default EXPANDED: collapsing by default hid whole answers behind "Show more".
   const [isExpanded, setIsExpanded] = useState(true)
   const exportMenuRef = useRef(null)
   const exportMenuBottomRef = useRef(null)

  // Close export dropdown when clicking outside it
  useEffect(() => {
    if (!showExportMenu && !showExportMenuBottom) return
    const handler = (e) => {
      if (exportMenuRef.current && !exportMenuRef.current.contains(e.target)) {
        setShowExportMenu(false)
      }
      if (exportMenuBottomRef.current && !exportMenuBottomRef.current.contains(e.target)) {
        setShowExportMenuBottom(false)
      }
    }
    document.addEventListener('mousedown', handler)
    return () => document.removeEventListener('mousedown', handler)
  }, [showExportMenu, showExportMenuBottom])

  const copy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(msg.content)
      setCopied(true)
      setTimeout(() => setCopied(false), 1500)
    } catch { /* clipboard blocked — nothing useful to say */ }
  }, [msg.content])

  // Build stable markdown components config — avoids new object on every render
  const markdownComponents = useMarkdownComponents(msg.content, onOpenArtifact)

  const formattedModelName = useMemo(() => {
    const rawModel = typeof msg.model === 'string' ? msg.model : (msg.model?.id || msg.model?.name || '')
    const rawProv = typeof msg.provider === 'string' ? msg.provider : (msg.provider?.id || msg.provider?.name || '')
    const mName = rawModel ? String(rawModel).split('/').pop() : ''
    const pName = rawProv === 'nvidia' ? 'NVIDIA (Free)'
      : rawProv === 'ollama' ? 'Ollama (local)'
      : rawProv === 'openrouter' ? 'OpenRouter'
      : rawProv === 'groq' ? 'Groq'
      : rawProv === 'openai' ? 'OpenAI'
      : rawProv === 'gemini' ? 'Gemini'
      : rawProv === 'anthropic' ? 'Anthropic Claude'
      : rawProv === 'deepseek' ? 'DeepSeek'
      : rawProv === 'xai' ? 'xAI Grok'
      : rawProv === 'mistral' ? 'Mistral AI'
      : rawProv === 'perplexity' ? 'Perplexity'
      : rawProv === 'local' ? 'On-device Model'
      : rawProv
    if (pName && mName) return `${pName} · ${mName}`
    if (mName) return mName
    if (pName) return pName
    return 'AI Model'
  }, [msg.model, msg.provider])

  const { reasoning, answer, actionChips, adaptiveParts } = useMemo(() => {
    const rawText = stripToolCallSyntax(typeof msg.content === 'string' ? msg.content : String(msg.content ?? ''))
    const s = splitReasoning(rawText)
    const strippedAnswer = stripToolCallSyntax(s.answer || '')
    const { cleanText, chips } = extractActionChips(strippedAnswer)
    // Parse adaptive cards from the cleaned text
    const { parts } = parseAdaptiveCards(cleanText)
    const hasCards = parts.some(p => p.type === 'card')
    return {
      reasoning: s.reasoning || '',
      answer: hasCards ? null : cleanText,
      adaptiveParts: hasCards ? parts : null,
      actionChips: chips,
    }
  }, [msg.content])

  // Provenance explanation state — expanded/collapsed
  const [showProvenance, setShowProvenance] = useState(false)
  const [hoveredSourceIdx, setHoveredSourceIdx] = useState(null)


  // Failed turns are rendered with actionable diagnosis, resolution recommendations, and copy tools
  if (msg.error) {
    const diagnosis = diagnoseError(msg.error)
    return (
      <div className="message assistant message-failed" role="alert">
        {/* If the model produced partial output before stopping, show it above
            the error card so the user doesn't lose what was already generated. */}
        {msg.content && msg.content.trim() && (
          <div className="message-partial-content">
            <div className="message-partial-label">⚡ Partial response (stopped early):</div>
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{msg.content}</ReactMarkdown>
          </div>
        )}
        <div className="message-error-card">
          <div className="message-error-header">
            <div className="message-error-title-wrap">
              <span className={`error-category-badge badge-${diagnosis.type}`}>
                {diagnosis.category}
              </span>
              <h4 className="message-error-title">{diagnosis.title}</h4>
            </div>
            <div className="message-error-actions">
              <button
                type="button"
                className="error-action-btn error-copy-btn"
                onClick={async () => {
                  try {
                    const dump = `Error: ${diagnosis.title}\nCategory: ${diagnosis.category}\nModel: ${msg.model || 'Unknown'}\nProvider: ${msg.provider || 'Unknown'}\nDetails: ${msg.error}`
                    await navigator.clipboard.writeText(dump)
                    setCopied(true)
                    setTimeout(() => setCopied(false), 2000)
                  } catch {}
                }}
                title="Copy error details"
              >
                {copied ? <Check size={12} /> : <Copy size={12} />}
                <span>{copied ? 'Copied' : 'Copy'}</span>
              </button>
            </div>
          </div>

          <div className="message-error-suggestion">
            {diagnosis.suggestion}
          </div>

          <div className="message-error-buttons">
            {onRetry && (
              <button type="button" className="error-btn-primary" onClick={onRetry}>
                <RefreshCw size={13} /> Retry Turn
              </button>
            )}

            {(diagnosis.actionType === 'settings' || diagnosis.type === 'auth') && onOpenSettings && (
              <button type="button" className="error-btn-secondary" onClick={onOpenSettings}>
                <Key size={13} /> {diagnosis.actionLabel || 'Configure Keys'}
              </button>
            )}

            {(diagnosis.actionType === 'autopick' || diagnosis.type === 'quota' || diagnosis.type === 'model_not_found' || diagnosis.type === 'stream_stall') && onAutoPick && (
              <button type="button" className="error-btn-secondary" onClick={() => onAutoPick(msg.provider)}>
                <Zap size={13} /> {diagnosis.actionLabel || 'Auto-Pick Model'}
              </button>
            )}
          </div>

          <details className="message-error-trace">
            <summary>
              <span>Technical Diagnostics</span>
            </summary>
            <pre className="message-error-raw">{msg.error}</pre>
          </details>
        </div>
      </div>
    )
  }


  return (
    <div className={`message ${msg.role}`}>
      <div className="message-role">
        <span className="message-who">{msg.role === 'user' ? 'You' : 'Yogatik'}</span>
        {msg.role === 'assistant' && (
          <span className="msg-model-badge" title={`Generated by ${formattedModelName}`}>
            {formattedModelName}
          </span>
        )}
        {msg.createdAt && <time className="message-time" dateTime={new Date(msg.createdAt).toISOString()}>{relativeTime(msg.createdAt)}</time>}

        <span className="message-actions" style={{ position: 'relative' }}>
          <button className="icon-btn" onClick={copy} title="Copy" aria-label="Copy message">
            {copied ? <Check size={12} /> : <Copy size={12} />}
          </button>
          {msg.role === 'assistant' && (
            <>
              <button className="icon-btn" onClick={() => onTTS(answer || msg.content)} title="Read aloud" aria-label="Read aloud">
                <Volume2 size={12} />
              </button>
              <span ref={exportMenuRef} style={{ position: 'relative' }}>
                <button
                  className="icon-btn"
                  onClick={() => setShowExportMenu(v => !v)}
                  title="Download as Word / PDF / MD"
                  aria-label="Download message"
                  aria-haspopup="true"
                  aria-expanded={showExportMenu}
                >
                  <Download size={12} />
                </button>
                {showExportMenu && (
                  <div
                    className="export-dropdown"
                    role="menu"
                    style={{
                      position: 'absolute', top: '100%', right: 0, zIndex: 100,
                      background: 'var(--bg-secondary, #1e1e2e)', border: '1px solid var(--border-color, rgba(255,255,255,0.1))',
                      borderRadius: 6, boxShadow: '0 4px 12px rgba(0,0,0,0.3)', padding: 4, display: 'flex', flexDirection: 'column', gap: 2, minWidth: 140,
                    }}
                  >
                    {[
                      { fmt: 'doc',          label: 'Word Document (.doc)',    icon: <FileText size={12} />,  title: 'document' },
                      { fmt: 'ppt',          label: 'PowerPoint (.ppt)',       icon: <FileText size={12} />,  title: 'presentation' },
                      { fmt: 'csv',          label: 'CSV Spreadsheet (.csv)',  icon: <FileText size={12} />,  title: 'data' },
                      { fmt: 'pdf',          label: 'PDF (.pdf)',              icon: <FileDown size={12} />,  title: 'document' },
                      { fmt: 'md',           label: 'Markdown (.md)',          icon: <Download size={12} />,  title: 'document' },
                    ].map(({ fmt, label, icon, title }) => (
                      <button
                        key={fmt}
                        role="menuitem"
                        className="dropdown-item"
                        onClick={() => { triggerDownload(msg.content, fmt, title); setShowExportMenu(false) }}
                        style={{ background: 'none', border: 'none', color: 'var(--text-primary)', padding: '6px 10px', fontSize: 12, textAlign: 'left', cursor: 'pointer', borderRadius: 4, display: 'flex', alignItems: 'center', gap: 6 }}
                      >
                        {icon} {label}
                      </button>
                    ))}
                  </div>
                )}
              </span>
            </>
          )}
          {msg.role === 'assistant' && onContinue && (
            <button className="icon-btn" onClick={onContinue} title="Continue / Resume task" aria-label="Continue this task">
              <Play size={12} />
            </button>
          )}
          {msg.role === 'assistant' && onRegenerate && (
            <button className="icon-btn" onClick={onRegenerate} title="Regenerate" aria-label="Regenerate this reply">
              <RefreshCw size={12} />
            </button>
          )}
          {msg.role === 'user' && onEdit && (
            <button className="icon-btn" onClick={() => onEdit(typeof msg.content === 'string' ? msg.content : '')}
              title="Edit this message — earlier turns branch into a new chat, the original is kept"
              aria-label="Edit this message">
              <Pencil size={12} />
            </button>
          )}
        </span>
      </div>

      {showToolCards && msg.toolResults && Object.keys(msg.toolResults).length > 0 && (
        <div className="tool-results">
          {Object.entries(msg.toolResults).map(([tool, result]) => (
            <ToolResultCard key={tool} tool={tool} result={result} />
          ))}
        </div>
      )}
      {msg.toolsUsed?.length > 0 && (
        <div className="tools-used">
          {msg.toolsUsed.map(t => {
            const Icon = TOOL_ICONS[t] || Wrench
            return <span key={t} className="tool-chip"><Icon size={10} /> {t}</span>
          })}
        </div>
      )}
      {msg.role === 'assistant' && (msg.toolsUsed?.length > 0 || msg.trace?.length > 0) && (
        <AgentWorkflowStepper
          trace={msg.trace || []}
          toolsUsed={msg.toolsUsed || []}
          modelName={formattedModelName}
          explanation={explainReply(msg, formattedModelName)}
        />
      )}
      {msg.file && (
        <div className="msg-attachment-badge">
          <FileText size={15} className="msg-attachment-icon" />
          <div className="msg-attachment-info">
            <span className="msg-attachment-name">{msg.file.name}</span>
            {msg.file.size ? (
              <span className="msg-attachment-size">
                {msg.file.size > 1048576
                  ? `${(msg.file.size / 1048576).toFixed(1)} MB`
                  : `${Math.round(msg.file.size / 1024)} KB`}
              </span>
            ) : null}
          </div>
        </div>
      )}
      {Array.isArray(msg.files) && msg.files.map((f, i) => (
        <div key={i} className="msg-attachment-badge">
          <FileText size={15} className="msg-attachment-icon" />
          <div className="msg-attachment-info">
            <span className="msg-attachment-name">{f.name}</span>
            {f.size ? (
              <span className="msg-attachment-size">
                {f.size > 1048576
                  ? `${(f.size / 1048576).toFixed(1)} MB`
                  : `${Math.round(f.size / 1024)} KB`}
              </span>
            ) : null}
          </div>
        </div>
      ))}
      {msg.image && (
        <div className="msg-image-wrap">
          <img src={msg.image} alt={msg.imageName || "Attached image"} className="msg-image"
            onClick={() => window.open(msg.image, '_blank', 'noopener')} />
          {msg.imageName && <span className="msg-image-caption">{msg.imageName}</span>}
        </div>
      )}
      {reasoning ? (
        <ReasoningAccordion reasoning={reasoning} isStreaming={false} />
      ) : null}
      {/* If there is no separate answer, show a clean action summary without duplicating internal thinking */}
      {msg.role === 'assistant' && typeof answer === 'string' && !answer && (
        <div className="message-content">
          {msg.toolsUsed?.length ? (
            <div className="message-tool-summary" style={{ color: 'var(--text-secondary, #888)', fontStyle: 'italic' }}>
              ✓ Completed actions ({msg.toolsUsed.join(', ')}). See the Thinking & Actions panel for step details.
            </div>
          ) : reasoning ? (
            <div className="message-empty" style={{ display: 'flex', flexDirection: 'column', gap: '8px', padding: '10px 14px', background: 'var(--bg-secondary, rgba(255, 255, 255, 0.04))', borderRadius: '8px', border: '1px solid var(--border-color, rgba(255, 255, 255, 0.1))' }}>
              <div style={{ color: 'var(--text-primary)', fontSize: '13px' }}>
                💡 The model formulated a plan in thinking but paused before executing.
              </div>
              <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                {(onContinue || onRegenerate) && (
                  <button
                    type="button"
                    className="small-btn"
                    style={{ background: 'var(--primary, #e06c75)', color: '#fff', border: 'none', padding: '5px 12px', borderRadius: '6px', cursor: 'pointer', fontSize: '12px', fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: '5px' }}
                    onClick={() => {
                      if (onContinue) onContinue()
                      else if (onRegenerate) onRegenerate()
                    }}
                  >
                    ⚡ Continue &amp; Execute Actions
                  </button>
                )}
              </div>
            </div>
          ) : (
            <div className="message-empty">
              (The model returned an empty response. Try Regenerate or a stronger model.)
            </div>
          )}
        </div>
      )}
       {/* Check if message content is long enough to warrant collapsing */}
       {typeof answer === 'string' && answer.length > 500 && msg.role === 'assistant' ? (
         <div className="message-content">
           {!isExpanded && (
             <>
               <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
                 {answer.substring(0, 500)}...
               </ReactMarkdown>
               <button
                 className="message-toggle-btn"
                 onClick={() => setIsExpanded(true)}
               >
                 Show more
               </button>
             </>
           )}
           {isExpanded && (
             <>
               <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
                 {answer}
               </ReactMarkdown>
               <button
                 className="message-toggle-btn"
                 onClick={() => setIsExpanded(false)}
               >
                 Show less
               </button>
             </>
           )}
         </div>
        ) : adaptiveParts ? (
          <div className="message-content">
            {adaptiveParts.map((part, pi) =>
              part.type === 'card'
                ? <AdaptiveCard key={`ac-${pi}`} data={part.data} cardIndex={pi} />
                : <ReactMarkdown key={`md-${pi}`} remarkPlugins={[remarkGfm]} components={markdownComponents}>{part.content}</ReactMarkdown>
            )}
          </div>
        ) : (
          <div className="message-content">
            <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>{answer}</ReactMarkdown>
          </div>
        )}
      {actionChips?.length > 0 && (
        <div className="message-action-chips" style={{ display: 'flex', flexWrap: 'wrap', gap: '8px', marginTop: '10px' }}>
          {actionChips.map((chip, idx) => (
            <button
              key={chip.id || idx}
              className="action-chip-btn"
              onClick={() => {
                window.dispatchEvent(new CustomEvent('yogatik:submit-prompt', { detail: { prompt: chip.prompt || chip.label } }))
              }}
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: '6px',
                padding: '5px 12px',
                borderRadius: '8px',
                background: 'rgba(59, 130, 246, 0.12)',
                border: '1px solid rgba(59, 130, 246, 0.3)',
                color: '#60a5fa',
                fontSize: '12px',
                fontWeight: 500,
                cursor: 'pointer',
                transition: 'all 0.15s ease',
              }}
              onMouseEnter={(e) => { e.currentTarget.style.background = 'rgba(59, 130, 246, 0.22)'; e.currentTarget.style.transform = 'translateY(-1px)' }}
              onMouseLeave={(e) => { e.currentTarget.style.background = 'rgba(59, 130, 246, 0.12)'; e.currentTarget.style.transform = 'none' }}
            >
              <span>⚡</span>
              <span>{chip.label}</span>
            </button>
          ))}
        </div>
      )}
      {msg.role === 'assistant' && (
        <FollowUpSuggestions
          content={answer || (typeof msg.content === 'string' ? msg.content : '')}
          onSelectSuggestion={(prompt) => {
            window.dispatchEvent(new CustomEvent('yogatik:submit-prompt', { detail: { prompt } }))
          }}
        />
      )}
      {msg.sources?.length > 0 && (
        <div className="sources" style={{ marginTop: 8, padding: '8px 12px', background: 'var(--bg-input, rgba(0,0,0,0.15))', borderRadius: 8, border: '1px solid var(--border)', position: 'relative' }}>
          <div className="sources-title" style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', marginBottom: 6, display: 'flex', alignItems: 'center', gap: 6 }}>
            <FileText size={12} /> Sources &amp; Retrieved Citations ({msg.sources.length})
          </div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
            {msg.sources.map((s, i) => {
              const label = s.title || (s.url ? s.url.replace(/^https?:\/\//, '').split('/')[0] : `Document ${i + 1}`)
              const scoreBadge = s.score ? ` (${Math.round(s.score * 100)}% match)` : ''
              const isHovered = hoveredSourceIdx === i

              return (
                <div
                  key={i}
                  style={{ position: 'relative', display: 'inline-flex' }}
                  onMouseEnter={() => setHoveredSourceIdx(i)}
                  onMouseLeave={() => setHoveredSourceIdx(null)}
                >
                  {s.url ? (
                    <a href={s.url} target="_blank" rel="noopener noreferrer" className="source-item source-chip" style={{ fontSize: 11, padding: '3px 8px', borderRadius: 4, background: 'var(--bg-secondary)', border: '1px solid var(--border)', display: 'inline-flex', alignItems: 'center', gap: 4, textDecoration: 'none', color: 'var(--accent)' }}>
                      🌐 {label}{scoreBadge}
                    </a>
                  ) : (
                    <span className="source-item source-chip" title={s.snippet || s.content || ''} style={{ fontSize: 11, padding: '3px 8px', borderRadius: 4, background: 'var(--bg-secondary)', border: '1px solid var(--border)', display: 'inline-flex', alignItems: 'center', gap: 4, color: 'var(--text-secondary)' }}>
                      📄 {label}{scoreBadge}
                    </span>
                  )}
                  {isHovered && s.url && (
                    <div style={{ position: 'absolute', bottom: 'calc(100% + 6px)', left: 0, zIndex: 9999 }}>
                      <CitationHoverCard source={s} index={i + 1} />
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        </div>
      )}
      {msg.role === 'assistant' && (msg.tokens || msg.tokSec || msg.ttfbMs) && (
        <div className="message-metrics-footer" style={{ display: 'flex', alignItems: 'center', gap: 10, fontSize: '11px', color: 'var(--text-muted, #71717a)', marginTop: 6, paddingTop: 4, borderTop: '1px solid var(--border-color, rgba(255,255,255,0.05))' }}>
          {msg.tokSec ? <span>⚡ {Number(msg.tokSec).toFixed(1)} tok/s</span> : null}
          {msg.ttfbMs ? <span>⏱️ TTFB {Math.round(msg.ttfbMs)}ms</span> : null}
          {msg.tokens ? <span>📊 {msg.tokens} tokens</span> : null}
        </div>
      )}

      {/* Phase 1: Provenance Badge — visible confidence/source attribution */}
      {msg.role === 'assistant' && (
        <div
          className="provenance-badge"
          role="status"
          aria-label={`Response from ${formattedModelName}${msg.toolsUsed?.length ? `, used ${msg.toolsUsed.length} tool${msg.toolsUsed.length === 1 ? '' : 's'}` : ''}${msg.sources?.length ? `, consulted ${msg.sources.length} source${msg.sources.length === 1 ? '' : 's'}` : ''}`}
        >
          <span className="provenance-chip">
            <Cpu size={9} aria-hidden="true" /> {formattedModelName || 'AI Model'}
          </span>
          {msg.toolsUsed?.length > 0 && (
            <span className="provenance-chip tools">
              <Wrench size={9} aria-hidden="true" /> {msg.toolsUsed.length} tool{msg.toolsUsed.length === 1 ? '' : 's'}
            </span>
          )}
          {msg.sources?.length > 0 && (
            <span className="provenance-chip sources">
              <FileText size={9} aria-hidden="true" /> {msg.sources.length} source{msg.sources.length === 1 ? '' : 's'}
            </span>
          )}
          {msg.ttfbMs && (
            <span className={`provenance-chip latency${msg.ttfbMs > 3000 ? ' bad' : msg.ttfbMs > 1000 ? ' warn' : ''}`} title="Time to first token">
              ⚡ {Math.round(msg.ttfbMs)}ms TTFB
            </span>
          )}
          {(msg.tokenCount || (answer || msg.content)?.length) ? (
            <span className="provenance-chip tokens" title="Estimated token count">
              <Zap size={9} aria-hidden="true" /> ~{Math.round(msg.tokenCount || ((answer || msg.content || '').length / 4)).toLocaleString()} tok
            </span>
          ) : null}
          <button
            type="button"
            onClick={() => setShowProvenance(p => !p)}
            style={{ background: 'none', border: 'none', color: 'inherit', cursor: 'pointer', padding: '0 2px', display: 'flex', alignItems: 'center', marginLeft: 'auto' }}
            title={showProvenance ? 'Hide explanation' : 'Why did I say this?'}
            aria-label={showProvenance ? 'Hide explanation' : 'Why did I say this?'}
            aria-expanded={showProvenance}
          >
            <Info size={11} />
          </button>
        </div>
      )}
      {showProvenance && msg.role === 'assistant' && (
        <div className="provenance-detail" role="note" aria-label="Response explanation">
          {explainReply(msg, formattedModelName)}
        </div>
      )}

      {msg.role === 'assistant' && (
        <div className="message-bottom-actions">
          <button
            type="button"
            className="bottom-action-btn"
            onClick={copy}
            title="Copy response"
            aria-label="Copy response"
          >
            {copied ? <Check size={14} style={{ color: 'var(--accent, #10b981)' }} /> : <Copy size={14} />}
          </button>
          <button
            type="button"
            className="bottom-action-btn"
            onClick={() => onTTS?.(answer || msg.content)}
            title="Read aloud"
            aria-label="Read aloud"
          >
            <Volume2 size={14} />
          </button>
          <div ref={exportMenuBottomRef} style={{ position: 'relative', display: 'inline-flex' }}>
            <button
              type="button"
              className="bottom-action-btn"
              onClick={() => setShowExportMenuBottom(v => !v)}
              title="Download response"
              aria-label="Download response"
              aria-haspopup="true"
              aria-expanded={showExportMenuBottom}
            >
              <Download size={14} />
            </button>
            {showExportMenuBottom && (
              <div
                className="export-dropdown export-dropdown-bottom"
                role="menu"
                style={{
                  position: 'absolute',
                  bottom: 'calc(100% + 6px)',
                  left: 0,
                  zIndex: 100,
                  background: 'var(--bg-secondary, #1e1e2e)',
                  border: '1px solid var(--border-color, rgba(255,255,255,0.12))',
                  borderRadius: 8,
                  boxShadow: '0 8px 24px rgba(0,0,0,0.4)',
                  padding: 4,
                  display: 'flex',
                  flexDirection: 'column',
                  gap: 2,
                  minWidth: 155,
                }}
              >
                {[
                  { fmt: 'doc', label: 'Word Document (.doc)', icon: <FileText size={12} />, title: 'document' },
                  { fmt: 'ppt', label: 'PowerPoint (.ppt)', icon: <FileText size={12} />, title: 'presentation' },
                  { fmt: 'csv', label: 'CSV Spreadsheet (.csv)', icon: <FileText size={12} />, title: 'data' },
                  { fmt: 'pdf', label: 'PDF (.pdf)', icon: <FileDown size={12} />, title: 'document' },
                  { fmt: 'md', label: 'Markdown (.md)', icon: <Download size={12} />, title: 'document' },
                ].map(({ fmt, label, icon, title }) => (
                  <button
                    key={fmt}
                    type="button"
                    role="menuitem"
                    className="dropdown-item"
                    onClick={() => { triggerDownload(msg.content, fmt, title); setShowExportMenuBottom(false) }}
                    style={{ background: 'none', border: 'none', color: 'var(--text-primary, #ddd)', padding: '6px 10px', fontSize: 12, textAlign: 'left', cursor: 'pointer', borderRadius: 4, display: 'flex', alignItems: 'center', gap: 6 }}
                  >
                    {icon} {label}
                  </button>
                ))}
              </div>
            )}
          </div>
          {onContinue && (
            <button
              type="button"
              className="bottom-action-btn"
              onClick={onContinue}
              title="Continue generating response"
              aria-label="Continue response"
            >
              <Play size={14} />
            </button>
          )}
          {(onRegenerate || onRetry) && (
            <button
              type="button"
              className="bottom-action-btn"
              onClick={onRegenerate || onRetry}
              title="Regenerate response"
              aria-label="Regenerate response"
            >
              <RefreshCw size={14} />
            </button>
          )}
        </div>
      )}
    </div>
  )
})

export { MessageBubble }
