import { describe, it, expect, vi, afterEach } from 'vitest'
import React from 'react'
import { render, screen, fireEvent, cleanup } from '@testing-library/react'
import { WebCompanionStudio, parseMarkdownCodeBlocks } from './WebCompanionStudio'

afterEach(() => {
  cleanup()
})

describe('parseMarkdownCodeBlocks helper', () => {
  it('parses single code block with language and line counts', () => {
    const md = 'Here is some code:\n```javascript\nconsole.log("hello world");\n```\nDone.'
    const blocks = parseMarkdownCodeBlocks(md)
    expect(blocks.length).toBe(1)
    expect(blocks[0].language).toBe('javascript')
    expect(blocks[0].code).toBe('console.log("hello world");\n')
    expect(blocks[0].filename).toBe('extracted_file_1.js')
  })

  it('detects explicit file comment in code block', () => {
    const md = '```typescript\n// filepath: src/utils/math.ts\nexport function add(a: number, b: number) { return a + b; }\n```'
    const blocks = parseMarkdownCodeBlocks(md)
    expect(blocks.length).toBe(1)
    expect(blocks[0].filename).toBe('src/utils/math.ts')
  })

  it('handles multiple code blocks of different languages', () => {
    const md = `
# Plan
\`\`\`html
<div class="test">Hello</div>
\`\`\`
And the python logic:
\`\`\`python
# file: solver.py
def solve(): return 42
\`\`\`
`
    const blocks = parseMarkdownCodeBlocks(md)
    expect(blocks.length).toBe(2)
    expect(blocks[0].language).toBe('html')
    expect(blocks[1].filename).toBe('solver.py')
    expect(blocks[1].language).toBe('python')
  })
})

describe('WebCompanionStudio Component', () => {
  it('renders studio banner, title, and tabs', () => {
    render(<WebCompanionStudio serviceName="Grok" serviceUrl="https://grok.com/" />)

    expect(screen.getByText(/Grok.com Web Companion Studio/)).toBeTruthy()
    expect(screen.getByText(/Launch Grok Companion/)).toBeTruthy()
    expect(screen.getByText(/Send File & Context/)).toBeTruthy()
    expect(screen.getByText(/Harvest Code Blocks/)).toBeTruthy()
    expect(screen.getByText(/Direct In-App AI/)).toBeTruthy()
  })

  it('allows switching between tabs', () => {
    render(<WebCompanionStudio serviceName="Gemini" serviceUrl="https://gemini.google.com/" />)

    // Click Harvest Code tab
    fireEvent.click(screen.getByText(/Harvest Code Blocks/))
    expect(screen.getByPlaceholderText(/Paste the response or code blocks generated by Gemini.com here/)).toBeTruthy()

    // Click Direct In-App AI tab
    fireEvent.click(screen.getByText(/Direct In-App AI/))
    expect(screen.getByText(/Native In-App Chat Integration/)).toBeTruthy()
  })

  it('parses pasted text and renders extracted code blocks in harvester tab', () => {
    render(<WebCompanionStudio serviceName="Grok" serviceUrl="https://grok.com/" />)

    fireEvent.click(screen.getByText(/Harvest Code Blocks/))
    const textarea = screen.getByPlaceholderText(/Paste the response or code blocks generated by Grok.com here/)

    fireEvent.change(textarea, {
      target: {
        value: '```jsx\n// file: Button.jsx\nexport default function Button() { return <button>Click</button> }\n```'
      }
    })

    expect(screen.getByText(/Extracted Code Blocks \(1\)/)).toBeTruthy()
    expect(screen.getByDisplayValue('Button.jsx')).toBeTruthy()
    expect(screen.getByText('Download')).toBeTruthy()
  })

  it('triggers switch service callback when switch button clicked', () => {
    const onSwitch = vi.fn()
    render(
      <WebCompanionStudio
        serviceName="Grok"
        onSwitchService={onSwitch}
        switchLabel="Switch to Gemini"
      />
    )

    const switchBtn = screen.getByText('Switch to Gemini')
    fireEvent.click(switchBtn)
    expect(onSwitch).toHaveBeenCalledTimes(1)
  })
})
