import * as fs from 'fs';
import * as path from 'path';
import { parse } from 'toml';
import type { CoreConfig, TerminalProfile } from '../shared/types';

const CONFIG_DIR = path.join(process.env.APPDATA || process.env.HOME || '', 'yogatik-terminal');
const CONFIG_FILE = path.join(CONFIG_DIR, 'config.toml');

let configCache: CoreConfig | null = null;
let watchers: fs.FSWatcher[] = [];

export function getConfigDir(): string {
  return CONFIG_DIR;
}

export function getConfigPath(): string {
  return CONFIG_FILE;
}

export function loadDefaultConfig(): CoreConfig {
  const defaultPath = path.join(__dirname, 'default.toml');
  const content = fs.readFileSync(defaultPath, 'utf-8');
  return parse(content) as CoreConfig;
}

export function ensureConfigDir(): void {
  if (!fs.existsSync(CONFIG_DIR)) {
    fs.mkdirSync(CONFIG_DIR, { recursive: true });
  }
}

export function loadConfig(): CoreConfig {
  if (configCache) return configCache;

  ensureConfigDir();

  if (!fs.existsSync(CONFIG_FILE)) {
    const defaultConfig = loadDefaultConfig();
    saveConfig(defaultConfig);
    configCache = defaultConfig;
    return defaultConfig;
  }

  try {
    const content = fs.readFileSync(CONFIG_FILE, 'utf-8');
    configCache = parse(content) as CoreConfig;
    // Merge with defaults to ensure all keys exist
    configCache = mergeWithDefaults(configCache, loadDefaultConfig());
    return configCache;
  } catch (error) {
    console.error('Failed to parse config, using defaults:', error);
    configCache = loadDefaultConfig();
    return configCache;
  }
}

function mergeWithDefaults(user: CoreConfig, defaults: CoreConfig): CoreConfig {
  const merged = { ...defaults, ...user };
  merged.rendering = { ...defaults.rendering, ...user.rendering };
  merged.performance = { ...defaults.performance, ...user.performance };
  merged.shellIntegration = { ...defaults.shellIntegration, ...user.shellIntegration };
  merged.security = { ...defaults.security, ...user.security };
  merged.advanced = { ...defaults.advanced, ...user.advanced };
  merged.profiles = { ...defaults.profiles, ...user.profiles };
  merged.keybindings = { ...defaults.keybindings, ...user.keybindings };

  // Deep merge each profile
  for (const [key, profile] of Object.entries(merged.profiles)) {
    const defaultProfile = defaults.profiles[key] || defaults.profiles.default;
    merged.profiles[key] = deepMerge(defaultProfile, profile) as TerminalProfile;
  }

  return merged;
}

function deepMerge(target: Record<string, any>, source: Record<string, any>): Record<string, any> {
  const result = { ...target };
  for (const [key, value] of Object.entries(source)) {
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      result[key] = deepMerge(target[key] || {}, value);
    } else {
      result[key] = value;
    }
  }
  return result;
}

export function saveConfig(config: CoreConfig): void {
  ensureConfigDir();
  const toml = serializeConfig(config);
  fs.writeFileSync(CONFIG_FILE, toml, 'utf-8');
  configCache = config;
}

function serializeConfig(config: CoreConfig): string {
  // Simple TOML serialization for our config structure
  const lines: string[] = [];

  lines.push('# Yogatik Terminal Configuration');
  lines.push('# This file is automatically generated on first run.');
  lines.push('# Edit with care - invalid TOML will fall back to defaults.');
  lines.push('');

  lines.push('[core]');
  lines.push(`default_profile = "${config.defaultProfile}"`);
  lines.push(`confirm_close = ${config.confirmClose}`);
  lines.push(`confirm_multiple_tabs = ${config.confirmMultipleTabs}`);
  lines.push(`startup_mode = "${config.startupMode}"`);
  lines.push(`check_updates = ${config.checkUpdates}`);
  lines.push('');

  lines.push('[core.rendering]');
  lines.push(`renderer = "${config.rendering.renderer}"`);
  lines.push(`gpu_acceleration = ${config.rendering.gpuAcceleration}`);
  lines.push(`vsync = ${config.rendering.vsync}`);
  lines.push(`max_fps = ${config.rendering.maxFps}`);
  lines.push('');

  lines.push('[core.performance]');
  lines.push(`scrollback_lines = ${config.performance.scrollbackLines}`);
  lines.push(`alt_scrollback_lines = ${config.performance.altScrollbackLines}`);
  lines.push(`repaint_throttle_ms = ${config.performance.repaintThrottleMs}`);
  lines.push(`dirty_row_threshold = ${config.performance.dirtyRowThreshold}`);
  lines.push('');

  for (const [profileId, profile] of Object.entries(config.profiles)) {
    lines.push(`[profiles.${profileId}]`);
    lines.push(`name = "${profile.name}"`);
    if (profile.shell === 'auto') {
      lines.push('shell = "auto"');
    } else {
      lines.push('shell = { path = "' + profile.shell.path.replace(/\\/g, '\\\\') + '", args = [' + profile.shell.args.map(a => '"' + a + '"').join(', ') + '], name = "' + profile.shell.name + '" }');
    }
    lines.push(`cwd = "${profile.cwd}"`);
    lines.push(`cols = ${profile.cols}`);
    lines.push(`rows = ${profile.rows}`);
    lines.push(`scrollback_lines = ${profile.scrollbackLines}`);
    lines.push('');

    lines.push('[profiles.' + profileId + '.font]');
    lines.push(`family = "${profile.font.family}"`);
    lines.push(`size = ${profile.font.size}`);
    lines.push(`line_height = ${profile.font.lineHeight}`);
    lines.push(`letter_spacing = ${profile.font.letterSpacing}`);
    lines.push(`ligatures = ${profile.font.ligatures}`);
    lines.push('fallback = [' + profile.font.fallbackFamilies.map(f => '"' + f + '"').join(', ') + ']');
    lines.push('');

    lines.push('[profiles.' + profileId + '.theme]');
    lines.push(`background = "${profile.theme.background}"`);
    lines.push(`foreground = "${profile.theme.foreground}"`);
    lines.push(`cursor = "${profile.theme.cursor}"`);
    lines.push(`cursor_accent = "${profile.theme.cursorAccent}"`);
    lines.push(`selection = "${profile.theme.selection}"`);
    lines.push(`ansi = { black = "${profile.theme.ansi.black}", red = "${profile.theme.ansi.red}", green = "${profile.theme.ansi.green}", yellow = "${profile.theme.ansi.yellow}", blue = "${profile.theme.ansi.blue}", magenta = "${profile.theme.ansi.magenta}", cyan = "${profile.theme.ansi.cyan}", white = "${profile.theme.ansi.white}" }`);
    lines.push(`ansi_bright = { black = "${profile.theme.ansiBright.black}", red = "${profile.theme.ansiBright.red}", green = "${profile.theme.ansiBright.green}", yellow = "${profile.theme.ansiBright.yellow}", blue = "${profile.theme.ansiBright.blue}", magenta = "${profile.theme.ansiBright.magenta}", cyan = "${profile.theme.ansiBright.cyan}", white = "${profile.theme.ansiBright.white}" }`);
    lines.push('');

    lines.push('[profiles.' + profileId + '.bell]');
    lines.push(`enabled = ${profile.bell.enabled}`);
    lines.push(`sound = "${profile.bell.sound}"`);
    lines.push(`visual = ${profile.bell.visual}`);
    lines.push(`flash_duration = ${profile.bell.flashDuration}`);
    lines.push('');

    lines.push('[profiles.' + profileId + '.cursor]');
    lines.push(`style = "${profile.cursor.style}"`);
    lines.push(`blink = ${profile.cursor.blink}`);
    lines.push(`blink_rate = ${profile.cursor.blinkRate}`);
    lines.push('');

    lines.push('[profiles.' + profileId + '.mouse]');
    lines.push(`enabled = ${profile.mouse.enabled}`);
    lines.push(`protocol = "${profile.mouse.protocol}"`);
    lines.push(`hide_when_typing = ${profile.mouse.hideWhenTyping}`);
    lines.push('');
  }

  lines.push('[keybindings]');
  for (const [key, action] of Object.entries(config.keybindings)) {
    lines.push(`"${key}" = "${action}"`);
  }
  lines.push('');

  lines.push('[shell_integration]');
  lines.push(`enabled = ${config.shellIntegration.enabled}`);
  lines.push(`auto_inject = ${config.shellIntegration.autoInject}`);
  lines.push(`osc7 = ${config.shellIntegration.osc7}`);
  lines.push(`osc133 = ${config.shellIntegration.osc133}`);
  lines.push(`bracket_paste = ${config.shellIntegration.bracketPaste}`);
  lines.push('');

  lines.push('[security]');
  lines.push(`pty_sandbox = ${config.security.ptySandbox}`);
  lines.push(`osc52_write_requires_gesture = ${config.security.osc52WriteRequiresGesture}`);
  lines.push(`deny_file_uris = ${config.security.denyFileUris}`);
  lines.push('denied_sequences = [' + config.security.deniedSequences.map(s => '"' + escapeString(s) + '"').join(', ') + ']');
  lines.push('');

  lines.push('[advanced]');
  lines.push(`experimental_kitty_graphics = ${config.advanced.experimentalKittyGraphics}`);
  lines.push(`experimental_sixel = ${config.advanced.experimentalSixel}`);
  lines.push(`log_pty_traffic = ${config.advanced.logPtyTraffic}`);
  lines.push(`audit_log = ${config.advanced.auditLog}`);

  return lines.join('\n');
}

function escapeString(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

export function watchConfig(callback: (config: CoreConfig) => void): () => void {
  ensureConfigDir();

  const watcher = fs.watch(CONFIG_FILE, { persistent: false }, (eventType) => {
    if (eventType === 'change') {
      // Debounce
      setTimeout(() => {
        configCache = null;
        const newConfig = loadConfig();
        callback(newConfig);
      }, 100);
    }
  });

  watchers.push(watcher);

  return () => {
    watcher.close();
    const idx = watchers.indexOf(watcher);
    if (idx >= 0) watchers.splice(idx, 1);
  };
}

export function getProfile(profileId: string): TerminalProfile | undefined {
  const config = loadConfig();
  return config.profiles[profileId] || config.profiles.default;
}

export function updateProfile(profileId: string, updates: Partial<TerminalProfile>): TerminalProfile {
  const config = loadConfig();
  const current = config.profiles[profileId] || config.profiles.default;
  const merged = deepMerge(current, updates) as TerminalProfile;
  config.profiles[profileId] = merged;
  saveConfig(config);
  return merged;
}

export function resetConfig(): CoreConfig {
  const defaultConfig = loadDefaultConfig();
  saveConfig(defaultConfig);
  return defaultConfig;
}

export type { CoreConfig, TerminalProfile };