/**
 * Auto-Skill Generator — learns from successful problem-solving sessions
 * and creates reusable skills automatically.
 * 
 * Analyzes agent conversations where tasks were completed successfully,
 * extracts the pattern (system prompt, tools used, workflow), and generates
 * a skill that can be reused for similar tasks.
 */

import { getSetting, setSetting } from './db'
import { getToolNames } from './tools/index'

const KEY = 'auto_skills'
const LEARNING_LOG = 'skill_learning_log'
const MIN_SUCCESSFUL_TURNS = 3  // Minimum turns to consider a session "successful"
const MIN_TOOL_CALLS = 2        // Minimum tool calls to consider it a skill-worthy task

/**
 * Analyze a conversation and extract skill-worthy patterns
 */
export async function analyzeConversationForSkills(conversationId, messages) {
  // Only analyze completed conversations with assistant responses
  const assistantMessages = messages.filter(m => m.role === 'assistant' && m.content)
  const userMessages = messages.filter(m => m.role === 'user' && m.content)
  
  if (assistantMessages.length < MIN_SUCCESSFUL_TURNS) return []
  if (userMessages.length === 0) return []
  
  // Count tool usage across the conversation
  const toolUsage = new Map()
  let totalToolCalls = 0
  
  for (const msg of messages) {
    if (msg.toolResults) {
      for (const [toolName, result] of Object.entries(msg.toolResults)) {
        if (result?.success !== false) { // Count successful tool calls
          toolUsage.set(toolName, (toolUsage.get(toolName) || 0) + 1)
          totalToolCalls++
        }
      }
    }
  }
  
  if (totalToolCalls < MIN_TOOL_CALLS) return []
  
  // Get the most used tools
  const topTools = Array.from(toolUsage.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8)
    .map(([name]) => name)
  
  // Extract the task pattern from the first user message
  const firstUserMsg = userMessages[0]?.content || ''
  const taskSummary = extractTaskSummary(firstUserMsg, messages)
  
  // Build a system prompt based on what the agent actually did
  const systemPrompt = buildSystemPromptFromConversation(messages, topTools)
  
  // Generate starter prompts
  const starters = generateStarters(firstUserMsg, taskSummary, topTools)
  
  // Create a skill candidate
  const skillCandidate = {
    id: `auto_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`,
    name: generateSkillName(taskSummary, topTools),
    description: `Auto-generated from a successful ${taskSummary.toLowerCase()} session`,
    system: systemPrompt,
    tools: topTools,
    starters,
    autoGenerated: true,
    sourceConversation: conversationId,
    createdAt: new Date().toISOString(),
    confidence: calculateConfidence(totalToolCalls, assistantMessages.length, topTools.length)
  }
  
  // Log the learning event
  await logLearningEvent(skillCandidate)
  
  return [skillCandidate]
}

/**
 * Extract a task summary from the first user message
 */
function extractTaskSummary(firstMsg, messages) {
  const keywords = {
    research: ['research', 'find', 'search', 'investigate', 'look up', 'latest', 'current'],
    coding: ['code', 'write', 'function', 'script', 'debug', 'fix', 'implement', 'build', 'create'],
    writing: ['write', 'draft', 'edit', 'proofread', 'rewrite', 'summarize', 'polish'],
    analysis: ['analyze', 'compare', 'chart', 'graph', 'data', 'statistics', 'trend'],
    planning: ['plan', 'schedule', 'organize', 'break down', 'steps', 'roadmap'],
    debugging: ['error', 'bug', 'issue', 'problem', 'fail', 'broken', 'not working'],
    learning: ['explain', 'how to', 'tutorial', 'learn', 'understand', 'teach']
  }
  
  const lower = firstMsg.toLowerCase()
  for (const [category, words] of Object.entries(keywords)) {
    if (words.some(w => lower.includes(w))) return category
  }
  return 'general'
}

/**
 * Build a system prompt from observing what the agent did
 */
function buildSystemPromptFromConversation(messages, topTools) {
  const toolDescriptions = {
    web_search: 'Search the web for current information',
    deep_research: 'Deep research with cited sources',
    code_execute: 'Write and run Python code',
    js_execute: 'Write and run JavaScript',
    doc_search: 'Search uploaded documents',
    wikipedia: 'Look up Wikipedia articles',
    scholar: 'Search academic papers',
    image_generate: 'Generate images',
    chart: 'Create charts and visualizations',
    video_render: 'Render videos',
    summarize: 'Summarize long content',
    ocr: 'Extract text from images',
    grammar_check: 'Check grammar and style',
    regex: 'Pattern matching and extraction',
    diff: 'Compare text differences',
    data_convert: 'Convert data formats',
    see: 'Read camera/screen',
    memory: 'Store/recall user facts',
    rss_feed: 'Fetch RSS feeds',
    youtube: 'Get YouTube video info'
  }
  
  const toolList = topTools.map(t => `- ${t}: ${toolDescriptions[t] || 'Specialized tool'}`).join('\n')
  
  return `You are a specialist agent auto-generated from a successful task completion.

ORIGINAL TASK PATTERN:
This skill was learned by observing an agent successfully complete a similar task using these tools:
${toolList}

APPROACH:
- Follow the same tool-use pattern that worked before
- Use tools in the observed sequence when applicable
- Prefer the same tool combinations that led to success
- Adapt the approach to the specific details of the new task

TOOL GUIDANCE:
${topTools.map(t => getToolGuidance(t)).join('\n')}

Be efficient. Use the proven tool pattern. Deliver a complete, working result.`
}

/**
 * Get guidance for a specific tool based on observed usage
 */
function getToolGuidance(tool) {
  const guidance = {
    web_search: 'Use for current facts, prices, releases — always verify with multiple sources',
    deep_research: 'Use for complex topics needing comprehensive cited answers',
    code_execute: 'Write complete, runnable code; verify by running it',
    js_execute: 'For quick JS computations or DOM-free logic',
    doc_search: 'Search user-uploaded documents first before web',
    wikipedia: 'Good for definitions, background, established facts',
    scholar: 'Use for academic claims, citations, evidence',
    image_generate: 'Use flux model with enhance=true for best quality',
    chart: 'Create clear visualizations with labeled axes',
    summarize: 'Extract key points, preserve important details',
    grammar_check: 'Run before finalizing any written output',
    regex: 'Use for pattern extraction, validation, parsing',
    diff: 'Compare versions, show precise changes',
    data_convert: 'Convert between CSV, JSON, YAML, TSV cleanly',
    see: 'Read camera/screen when visual context is needed',
    memory: 'Store durable user facts; recall automatically',
    rss_feed: 'Fetch latest feeds for current content',
    youtube: 'Get metadata; transcripts often unavailable'
  }
  return guidance[tool] || 'Use as needed for the task'
}

/**
 * Generate starter prompts for the skill
 */
function generateStarters(firstMsg, taskSummary, topTools) {
  const baseStarters = {
    research: [
      'Research {{topic}} and give me a cited summary',
      'What\'s the latest on {{topic}}?',
      'Compare the evidence for and against {{claim}}'
    ],
    coding: [
      'Write a {{language}} function that {{task}}',
      'Debug this code: {{code}}',
      'Create a script to {{task}}'
    ],
    writing: [
      'Draft a {{type}} about {{topic}}',
      'Proofread and improve: {{text}}',
      'Rewrite this in a {{tone}} tone: {{text}}'
    ],
    analysis: [
      'Analyze this data: {{data}}',
      'Chart the trend in {{data}}',
      'Find patterns and outliers in {{data}}'
    ],
    planning: [
      'Create a plan for {{goal}}',
      'Break down {{project}} into steps',
      'What are the steps to {{objective}}?'
    ],
    debugging: [
      'Help me fix this error: {{error}}',
      'Why is {{code}} not working?',
      'Debug this issue: {{description}}'
    ],
    learning: [
      'Explain {{concept}} simply',
      'How do I {{task}}?',
      'Teach me about {{topic}}'
    ],
    general: [
      'Help me with {{task}}',
      'Solve this: {{problem}}',
      'Guide me through {{process}}'
    ]
  }
  
  const starters = baseStarters[taskSummary] || baseStarters.general
  
  // Customize based on tools used
  const toolSpecific = []
  if (topTools.includes('web_search') || topTools.includes('deep_research')) {
    toolSpecific.push('Find current information about {{topic}}')
  }
  if (topTools.includes('code_execute')) {
    toolSpecific.push('Write and test code for {{task}}')
  }
  if (topTools.includes('chart')) {
    toolSpecific.push('Visualize {{data}} as a chart')
  }
  if (topTools.includes('doc_search')) {
    toolSpecific.push('Search my documents for {{query}}')
  }
  
  return [...starters.slice(0, 2), ...toolSpecific.slice(0, 2)]
}

/**
 * Generate a skill name from the task
 */
function generateSkillName(taskSummary, topTools) {
  const prefixes = {
    research: 'Research',
    coding: 'Code',
    writing: 'Writing',
    analysis: 'Data Analysis',
    planning: 'Planning',
    debugging: 'Debugging',
    learning: 'Learning',
    general: 'Assistant'
  }
  
  const toolSuffix = topTools.length > 0 
    ? ` + ${topTools[0].replace(/_/g, ' ')}` 
    : ''
  
  return `${prefixes[taskSummary] || 'Custom'} Specialist${toolSuffix}`
}

/**
 * Calculate confidence score for the auto-generated skill
 */
function calculateConfidence(toolCalls, turns, toolTypes) {
  let score = 0.3 // Base
  score += Math.min(toolCalls / 10, 0.3) // More tool calls = more confident
  score += Math.min(turns / 10, 0.2) // More turns = more complete
  score += Math.min(toolTypes / 8, 0.2) // More tool variety = more generalizable
  return Math.min(score, 0.95)
}

/**
 * Log a learning event for review
 */
async function logLearningEvent(skillCandidate) {
  try {
    const log = (await getSetting(LEARNING_LOG, [])) || []
    log.unshift({
      skillId: skillCandidate.id,
      name: skillCandidate.name,
      sourceConversation: skillCandidate.sourceConversation,
      confidence: skillCandidate.confidence,
      tools: skillCandidate.tools,
      createdAt: skillCandidate.createdAt
    })
    // Keep last 100 learning events
    await setSetting(LEARNING_LOG, log.slice(0, 100))
  } catch {
    // Silently fail
  }
}

/**
 * Get all learning log entries
 */
export async function getLearningLog() {
  return (await getSetting(LEARNING_LOG, [])) || []
}

/**
 * Clear the learning log
 */
export async function clearLearningLog() {
  await setSetting(LEARNING_LOG, [])
}

/**
 * Get pending auto-generated skills (not yet saved)
 */
export async function getPendingAutoSkills() {
  return (await getSetting(KEY, [])) || []
}

/**
 * Save an auto-generated skill as a permanent skill
 */
export async function promoteAutoSkill(skillId) {
  const pending = await getPendingAutoSkills()
  const skill = pending.find(s => s.id === skillId)
  if (!skill) throw new Error('Auto-skill not found')
  
  // Import upsertSkill from skills.js
  const { upsertSkill } = await import('./skills')
  const saved = await upsertSkill({
    ...skill,
    id: skill.id.replace('auto_', 'skill_'), // New ID for permanent skill
    autoGenerated: false,
    promotedAt: new Date().toISOString()
  })
  
  // Remove from pending
  await setSetting(KEY, pending.filter(s => s.id !== skillId))
  
  return saved
}

/**
 * Dismiss an auto-generated skill
 */
export async function dismissAutoSkill(skillId) {
  const pending = await getPendingAutoSkills()
  await setSetting(KEY, pending.filter(s => s.id !== skillId))
}

/**
 * Process all recent conversations for skill learning
 * Called periodically or on demand
 */
export async function processConversationsForLearning() {
  const { getConversations, getConversation } = await import('./db')
  const conversations = await getConversations()
  
  const processed = (await getSetting('skill_learning_processed', [])) || []
  const newCandidates = []
  
  for (const conv of conversations) {
    if (processed.includes(conv.id)) continue
    if (!conv.messages || conv.messages.length < MIN_SUCCESSFUL_TURNS) continue
    
    const candidates = await analyzeConversationForSkills(conv.id, conv.messages)
    newCandidates.push(...candidates)
    
    processed.push(conv.id)
  }
  
  if (newCandidates.length > 0) {
    const existing = (await getSetting(KEY, [])) || []
    await setSetting(KEY, [...newCandidates, ...existing].slice(0, 50))
  }
  
  await setSetting('skill_learning_processed', processed.slice(-200))
  
  return newCandidates
}

/**
 * Enable/disable auto-skill learning
 */
export async function setAutoSkillLearning(enabled) {
  await setSetting('auto_skill_learning', enabled === true)
}

export async function getAutoSkillLearning() {
  return (await getSetting('auto_skill_learning', true)) === true
}