/**
 * Export a conversation to a shareable file — clean Markdown, a self-contained
 * styled HTML page, or a PDF. No backend: the file is the share. Pure builders
 * (markdown/html) are unit-tested; downloadChat wires up the browser download.
 */

/** Multimodal messages store content as an array of parts; keep the text. */
function textOf(content) {
  if (typeof content === 'string') return content
  if (Array.isArray(content)) {
    return content.filter(p => p?.type === 'text' || typeof p === 'string')
      .map(p => (typeof p === 'string' ? p : p.text)).join('\n')
  }
  return String(content ?? '')
}

const who = (role) => (role === 'user' ? 'You' : 'Yogatik')

export function conversationToMarkdown(conv) {
  const title = conv?.title || 'Conversation'
  const msgs = (conv?.messages || []).filter(m => m.role !== 'system')
  const body = msgs.map(m => `**${who(m.role)}:**\n\n${textOf(m.content).trim()}`).join('\n\n---\n\n')
  return `# ${title}\n\n${body}\n`
}

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

// Minimal, dependency-free Markdown → HTML for message bodies (headings, code,
// bold/italic, inline code, links, line breaks). Good enough for a readable export.
function mdInline(s) {
  return esc(s)
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/(^|[^*])\*([^*]+)\*/g, '$1<em>$2</em>')
    .replace(/\[([^\]]+)\]\((https?:[^)]+)\)/g, '<a href="$2">$1</a>')
}
function mdBlock(text) {
  const out = []
  const lines = String(text).split('\n')
  let inCode = false, code = []
  for (const line of lines) {
    if (/^```/.test(line)) {
      if (inCode) { out.push(`<pre><code>${esc(code.join('\n'))}</code></pre>`); code = []; inCode = false }
      else inCode = true
      continue
    }
    if (inCode) { code.push(line); continue }
    if (/^#{1,6}\s/.test(line)) {
      const level = line.match(/^#+/)[0].length
      out.push(`<h${level}>${mdInline(line.replace(/^#+\s/, ''))}</h${level}>`)
    } else if (/^\s*[-*]\s/.test(line)) {
      out.push(`<li>${mdInline(line.replace(/^\s*[-*]\s/, ''))}</li>`)
    } else if (line.trim() === '') {
      out.push('')
    } else {
      out.push(`<p>${mdInline(line)}</p>`)
    }
  }
  if (inCode && code.length) out.push(`<pre><code>${esc(code.join('\n'))}</code></pre>`)
  return out.join('\n').replace(/(<li>[\s\S]*?<\/li>)(?!\s*<li>)/g, '<ul>$1</ul>')
}

export function conversationToHtml(conv) {
  const title = conv?.title || 'Conversation'
  const msgs = (conv?.messages || []).filter(m => m.role !== 'system')
  const rows = msgs.map(m => `
    <div class="msg ${m.role}">
      <div class="role">${who(m.role)}</div>
      <div class="body">${mdBlock(textOf(m.content).trim())}</div>
    </div>`).join('\n')
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>
  :root{--brand:#ff6b35}
  *{box-sizing:border-box}
  body{font-family:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;line-height:1.6;color:#1a1a1a;background:#fafafa;margin:0;padding:32px 16px}
  .wrap{max-width:760px;margin:0 auto}
  h1.title{font-size:26px;margin:0 0 6px}
  .sub{color:#888;font-size:13px;margin-bottom:28px}
  .msg{border-radius:14px;padding:16px 18px;margin:14px 0}
  .msg.user{background:#fff;border:1px solid #eee}
  .msg.assistant{background:#fff7f3;border:1px solid #ffe3d4}
  .role{font-weight:700;font-size:12px;text-transform:uppercase;letter-spacing:.04em;color:var(--brand);margin-bottom:8px}
  .msg.user .role{color:#555}
  .body :first-child{margin-top:0}.body :last-child{margin-bottom:0}
  pre{background:#0f1522;color:#e8edf4;padding:12px;border-radius:8px;overflow:auto;font-size:13px}
  code{font-family:ui-monospace,Menlo,Consolas,monospace}
  p code{background:#eef;border-radius:4px;padding:0 4px}
  a{color:var(--brand)}
  footer{margin-top:34px;text-align:center;color:#aaa;font-size:12px}
  @media print{body{background:#fff;padding:0}.msg{break-inside:avoid}}
</style></head><body><div class="wrap">
  <h1 class="title">${esc(title)}</h1>
  <div class="sub">Exported from Yogatik · ${new Date().toLocaleString()}</div>
  ${rows}
  <footer>Generated by Yogatik — yogatik.web.app</footer>
</div></body></html>`
}

function triggerDownload(blob, filename) {
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = filename
  a.click()
  setTimeout(() => URL.revokeObjectURL(a.href), 1000)
}

const safeName = (t) => (t || 'conversation').replace(/[^a-z0-9\- ]+/gi, '').trim().slice(0, 60) || 'conversation'

/** Download the conversation in the given format: 'md' | 'html' | 'pdf'. */
export async function downloadChat(conv, format = 'md') {
  const name = safeName(conv?.title)
  if (format === 'md') {
    triggerDownload(new Blob([conversationToMarkdown(conv)], { type: 'text/markdown' }), `${name}.md`)
    return
  }
  const html = conversationToHtml(conv)
  if (format === 'html') {
    triggerDownload(new Blob([html], { type: 'text/html' }), `${name}.html`)
    return
  }
  if (format === 'pdf') {
    const { generatePdfDoc } = await import('./tools/docGenerator')
    const md = conversationToMarkdown(conv)
    const res = await generatePdfDoc({ title: name, content: md, author: 'Yogatik AI' })
    triggerDownload(res.blob, res.filename)
  }
}
