/**
 * Overleaf / IEEE LaTeX Project Packager
 * Bundles generated LaTeX paper drafts, BibTeX citations, and standard IEEEtran templates
 */

export interface OverleafBundleFile {
  filename: string
  content: string
  isBinary?: boolean
}

export interface OverleafProjectBundle {
  projectName: string
  files: OverleafBundleFile[]
  summary: string
}

export function getLatexmkrc(): string {
  return `$pdf_mode = 1;
$bibtex_use = 2;
$pdflatex = 'pdflatex -interaction=nonstopmode -shell-escape %O %S';
$max_repeat = 5;
@generated_exts = qw(aux bbl blg log out synctex.gz fls fdb_latexmk);
`
}

/**
 * Generates standard IEEEtran.cls skeleton header / macro definitions for standalone compilation
 */
export function generateIEEEtranClsStub(): string {
  return `% IEEEtran stub file for standard LaTeX distribution
\\ProvidesClass{IEEEtran}[2026/01/01 IEEE Standard Template Class]
\\LoadClass[10pt,conference,compsoc]{article}
\\RequirePackage{amsmath,amssymb,amsfonts,graphicx,cite,booktabs,url,algorithmic}
\\setlength{\\textwidth}{7in}
\\setlength{\\textheight}{9.25in}
\\setlength{\\oddsidemargin}{-0.25in}
\\setlength{\\evensidemargin}{-0.25in}
\\setlength{\\topmargin}{-0.5in}
\\newcommand{\\IEEEauthorblockN}[1]{\\textbf{#1}\\\\ }
\\newcommand{\\IEEEauthorblockA}[1]{\\textit{#1}\\\\ }
\\newcommand{\\IEEEkeywords}[1]{\\paragraph{Keywords:} #1}
`.trim()
}

/**
 * Packages an academic paper draft into an Overleaf-ready project structure
 */
export function buildOverleafProject(data: {
  title: string
  authors: string[]
  abstract: string
  keywords: string[]
  introduction: string
  relatedWork: string
  methodology: string
  experimentalResults: string
  conclusion: string
  bibtexEntries: string[]
  acknowledgments?: string
}): OverleafProjectBundle {
  const safeName = data.title.replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 40) || 'IEEE_Paper'

  const mainTex = `\\documentclass[conference]{IEEEtran}
\\usepackage{amsmath,amsfonts,amssymb}
\\usepackage{graphicx}
\\usepackage{cite}
\\usepackage{booktabs}
\\usepackage{url}

\\begin{document}

\\title{${data.title}}

\\author{${data.authors.map((a) => `\\IEEEauthorblockN{${a}}`).join(' \\and ')}}

\\maketitle

\\begin{abstract}
${data.abstract}
\\end{abstract}

\\begin{IEEEkeywords}
${data.keywords.join(', ')}
\\end{IEEEkeywords}

\\section{Introduction}
${data.introduction}

\\section{Related Work \\& State of the Art}
${data.relatedWork}

\\section{Proposed Architecture \\& Methodology}
${data.methodology}

\\section{Experimental Results \\& Verification}
${data.experimentalResults}

\\section{Conclusion \\& Future Work}
${data.conclusion}

${data.acknowledgments ? `\\section*{Acknowledgment}\n${data.acknowledgments}\n` : ''}
\\bibliographystyle{IEEEtran}
\\bibliography{references}

\\end{document}
`

  const referencesBib =
    data.bibtexEntries.join('\n\n') ||
    `@article{ref1,
  author = {Smith, John and Doe, Jane},
  title = {Foundations of Modern VLSI Design Verification},
  journal = {IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems},
  volume = {43},
  number = {4},
  pages = {1120--1135},
  year = {2024}
}`

  const readmeMd = `# ${data.title}

This Overleaf / LaTeX project package was automatically generated by **Yogatik Research Assistant**.

## Project Files
- \`main.tex\`: Main IEEE Transactions formatted manuscript
- \`references.bib\`: Clean BibTeX citations
- \`IEEEtran.cls\`: Class style definitions
- \`latexmkrc\`: Automated compilation configuration
- \`figures/\`: Target directory for EPS, PDF, and PNG diagram assets
- \`tables/\`: Target directory for modular table data

## How to Compile in Overleaf
1. Upload this zip archive to [Overleaf](https://www.overleaf.com) via **New Project > Upload Project**.
2. Select \`main.tex\` as the root document.
3. Choose **pdfLaTeX** or **XeLaTeX** engine.
`

  const gitignore = `*.aux
*.bbl
*.blg
*.log
*.out
*.synctex.gz
*.fls
*.fdb_latexmk
*.toc
`

  const files: OverleafBundleFile[] = [
    { filename: 'main.tex', content: mainTex },
    { filename: 'references.bib', content: referencesBib },
    { filename: 'IEEEtran.cls', content: generateIEEEtranClsStub() },
    { filename: 'latexmkrc', content: getLatexmkrc() },
    { filename: 'README.md', content: readmeMd },
    { filename: '.gitignore', content: gitignore },
    { filename: 'figures/.gitkeep', content: '' },
    { filename: 'tables/.gitkeep', content: '' },
  ]

  return {
    projectName: safeName,
    files,
    summary: `Overleaf bundle generated with ${files.length} structured files (main.tex, references.bib, latexmkrc, IEEEtran.cls, README.md, .gitignore, and figure/table assets).`,
  }
}
